### ISSUE TITLE
最終更新日について

### ISSUE THREAD

**Issue by UedaShinichiro** [codeforosaka/covid19#105]
## 改善詳細 / Details of Improvement
最終更新 2020/03/19 15:00　としているところ、
最終更新 2020/03/19 というふうに時間を非表示としてもらえるでしょうか。
（色々お願いしてしまい、すみません）

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by teppei696** [comment]
やりますー
