### ISSUE TITLE
PR作成時にnetlifyで確認できるようにしたい

### ISSUE THREAD

**Issue by teppei696** [codeforosaka/covid19#108]
## 改善詳細 / Details of Improvement
- PR作成時にnetlifyで確認できるようにしたい

## 期待する見せ方・挙動 / Expected behavior
- PR作成→レビュアーが実際に動くものを見てレビューできる

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by sumihiro3** [comment]
Netlify のdeploy-preview を使えばPull Request のプレビュー用ビルドを走らせることが出来ます。
ビルド完了後、下記スクリーンショットのようにPull Request ページの赤枠部にあるリンクから遷移するとNetlify 上でPull Request のプレビューを見ることが出来ます。

![deploy-preview](https://raw.githubusercontent.com/sumihiro3/covid19/sumihiro3/108/static/108_deploy-preview.png)

### ドキュメント
- https://docs.netlify.com/site-deploys/overview/#deploy-preview-controls

### お試し
- [Pull Request page](https://github.com/sumihiro3/covid19/pull/1)
- [Preview on Netlify](https://deploy-preview-1--keen-khorana-dc1076.netlify.com/)
  -  テスト用に画面上部のタイトル「大阪府の最新感染動向」右側へ「（#108 Test）」を追記しています

**Comment by teppei696** [comment]
これも

https://tech.moyashidaisuke.com/entry/netlify-deploy-preview

**Comment by teppei696** [comment]
@sumihiro3 
実現できましたー
ありがとうございましたー
