### ISSUE TITLE
多言語で表示できるようにしたい

### ISSUE THREAD

**Issue by teppei696** [codeforosaka/covid19#110]
## 改善詳細 / Details of Improvement
- 多言語対応を実施したい

## 期待する見せ方・挙動 / Expected behavior
- 多言語対応が実施できる仕組みになっている
- ※大きな話になるので、ここで議論した上で細かくissueを分割していきたい

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Blue-Tone** [comment]
[東京のソース](https://github.com/tokyo-metropolitan-gov/covid19)を参考にすると良さそう。
[東京のサイト](https://stopcovid19.metro.tokyo.lg.jp/)のサイドメニュー下側に言語選択がある。

関連するソース
- covid19_tokyo/components/LanguageSelector.vue
- covid19_tokyo/components/SideNavigation.vue

**Comment by Blue-Tone** [comment]
言語選択を表示するところまで移植できました。
https://github.com/Blue-Tone/covid19/tree/feature/issue-110-LauguageSelector

以下の問題が残っています。
- サイドメニューが英語で表示されるようになってしまった。(SideNavigation.vueのi18nの変換が効かなくなったようです。)
- 言語選択すると「多言語対応選択メニュー」は翻訳されるが、全体は翻訳されていない。

**Comment by Blue-Tone** [comment]
夜22時ぐらいまでは作業進められないので、どなたか作業進められる方はお願いします。

**Comment by mfmfuyu** [comment]
ガッツリと作業はできないのですが、こちら確認してみようと思います

**Comment by mfmfuyu** [comment]
ひとまず、サイドメニューと「当サイトについて」は翻訳されるようにしました。
残りは後ほど対応しようと思います。

https://github.com/mfmfuyu/covid19/tree/issue-110-LauguageSelector

**Comment by mfmfuyu** [comment]
連絡が遅くなってしまい、申し訳ありません。
作業が残ってしまっている「府内の最新感染動向」ですが、
今日は作業に取り掛かれるのが夕方ごろになりそうので、
もし作業ができる方がいましたら、続きをお願いしたいです。

**Comment by Blue-Tone** [comment]
codeforosaka/covid19のリポジトリにブランチ作成しました。
こちらにPRしていただけると助かります。
https://github.com/codeforosaka/covid19/tree/feature/issue-110-LauguageSelector

**Comment by Blue-Tone** [comment]
PRして、マージしました。
https://github.com/codeforosaka/covid19/pull/143

**Comment by mfmfuyu** [comment]
すみません、ドタバタしておりまして対応ができませんでした
PRの方ありがとうございます

**Comment by Blue-Tone** [comment]
developmentブランチをマージして、ローカルで動作確認したところ、以下のエラーが出ています。
こちらで少しみてみます。

```

covid19 | ℹ Type checking in progress...
covid19 | 
covid19 |  ERROR  ERROR in /app/components/LanguageSelector.vue(46,24):
covid19 | 46:24 Property 'setLocale' does not exist on type 'VueI18n & IVueI18n'.
covid19 |     44 |   methods: {
covid19 |     45 |     handleChangeLanguage() {
covid19 |   > 46 |       this.$root.$i18n.setLocale(this.currentLocaleCode)
covid19 |        |                        ^
covid19 |     47 |     }
covid19 |     48 |   }
covid19 |     49 | })
covid19 | 
covid19 | 
covid19 |  ERROR  ERROR in /app/pages/about.vue(231,3):
covid19 | 231:3 'head' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.
covid19 |     229 |     TextCard
covid19 |     230 |   },
covid19 |   > 231 |   head() {
covid19 |         |   ^
covid19 |     232 |     return {
covid19 |     233 |       title: this.$t('当サイトについて') as string
covid19 |     234 |     }
covid19 | 
covid19 | 
covid19 |  ERROR  ERROR in /app/pages/about.vue(233,19):
covid19 | 233:19 Property '$t' does not exist on type '{ components: { TextCard: typeof TextCard; }; head(): any; }'.
covid19 |     231 |   head() {
covid19 |     232 |     return {
covid19 |   > 233 |       title: this.$t('当サイトについて') as string
covid19 |         |                   ^
covid19 |     234 |     }
covid19 |     235 |   }
covid19 |     236 | }
covid19 | 
covid19 | ℹ Version: typescript 3.8.3
covid19 | ℹ Time: 31835ms

```

**Comment by mfmfuyu** [comment]
> developmentブランチをマージして、ローカルで動作確認したところ、以下のエラーが出て言語選択が表示できていません。→docker-compose upしなおしたら表示できた？
> こちらで少し調査してみます。

こちら見落としてしまっていたようです、すみません。
ご確認ありがとうございます。

**Comment by Blue-Tone** [comment]
いえいえ。自分も見落としていたので。
どうやら、ERRORと出ていますが、TypeScriptの？ワーニングのような気がしました。
目に見える実害はなさそうなので、エラーの解消は一旦優先度下げて良いかと思いました。

**Comment by ryo-is** [comment]
> Property 'setLocale' does not exist on type 'VueI18n & IVueI18n'.

これに関しては i18n の型宣言が読み込めていないだけなので、`tsconfig.json` に少し追記すれば解消されますので、対応してPR出しても問題ないでしょうか？

**Comment by Blue-Tone** [comment]
> > Property 'setLocale' does not exist on type 'VueI18n & IVueI18n'.
> 
> これに関しては i18n の型宣言が読み込めていないだけなので、`tsconfig.json` に少し追記すれば解消されますので、対応してPR出しても問題ないでしょうか？

@ryo-is ありがとうございます。
PR、是非お願いします！

**Comment by ryo-is** [comment]
@Blue-Tone 
対応してPRを出しましたので確認お願いいたします 🙇

**Comment by Blue-Tone** [comment]
@ryo-is ありがとうございます！マージしました！

**Comment by teppei696** [comment]
マージ済みのため、クローズ
