### ISSUE TITLE
「陽性者の属性」の列名修正と補足追記について

### ISSUE THREAD

**Issue by UedaShinichiro** [codeforosaka/covid19#118]
## 改善詳細 / Details of Improvement
・列名：陰性確認済を「退院」に名称変更（再度の戻し作業となり申し訳ないです）

・「陰性確認済（退院者累計）」の注釈と同じように以下を「陽性者の属性」へ追記
※退院とは新型コロナウイルス感染症が治癒した者
※退院には死亡退院を含む

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by teppei696** [comment]
やりますー
