### ISSUE TITLE
OGP画像の背景を白色にする

### ISSUE THREAD

**Issue by mfmfuyu** [codeforosaka/covid19#136]
## 改善詳細 / Details of Improvement
- OGP画像の背景が透明なのでダークテーマ利用時などに見づらいので改善したい

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/54523771/77432386-53f89e80-6e21-11ea-99b7-e7a99148364e.png)

## 期待する見せ方・挙動 / Expected behavior
- OGP画像の背景を白色にする

手元に編集済みの画像があるので問題なければすぐにPR作成できます。

**Comment by teppei696** [comment]
僕が適当に作ってしまったogp画像なのでぜひぜひ修正をお願いしたいです

**Comment by mfmfuyu** [comment]
ひとまず、背景を白色で塗りつぶしたものでPRを作成しました
