### ISSUE TITLE
READMEでの画像のリンク切れなどの修正

### ISSUE THREAD

**Issue by mfmfuyu** [codeforosaka/covid19#137]
## 起こっている問題 / The Problem
- READMEにて画像のリンク切れが発生してしまっている、またリンクの飛び先も対策サイトではなくGitHubのCDN？になっており「Non-Image content-type returned」と表示されてしまっている

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/54523771/77432872-fa44a400-6e21-11ea-94c7-9f493cee2791.png)

## 期待する見せ方・挙動 / Expected Behavior
- ロゴ画像を表示し、リンク先を対策サイトに修正する

**Comment by teppei696** [comment]
すいません。これってなんかイカした画像を作ってはりたいなーって思ってリンクにしたまんまでした。。。
一旦リンクにするだけでよさそうですね。。。

**Comment by mfmfuyu** [comment]
そうだったのですね、リンクの修正こちらの方で対応しようと思います。
