### ISSUE TITLE
各ページを多言語化し、翻訳定義を作成する

### ISSUE THREAD

**Issue by Blue-Tone** [codeforosaka/covid19#152]
親Issue : 多言語で表示できるようにしたい #110 

## 改善詳細 / Details of Improvement
- 各ページの翻訳文字を$t()で翻訳対象とする。
- assets/locales/*.json に対応する翻訳を定義する。まずは、日本語、やさしい日本語、英語を対象とする。

翻訳定義が無いものは、ChromeのF12のデバッグ画面でWarningで表示されます。

## 1. サイドメニュー:components/SideNavigation.vue
- [x] $t()対応
- [ ] ja
- [ ] ja-Hira
- [ ] en

## 2. このページについて:pages/about.vue 
- [x] $t()対応
- [ ] ja
- [ ] ja-Hira
- [ ] en

## 3. 大阪府の最新感染動向
- [x] $t()対応
- [ ] ja
- [ ] ja-Hira
- [ ] en

## 期待する見せ方・挙動 / Expected behavior
- 各ページが選択した言語で表示される

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mfmfuyu** [comment]
「府内の最新感染動向」についてですが、もし誰もまだ作業に入っていない状態でしたら私が引き続き対応を行っていこうと思います。

また、翻訳ファイルについてですが最初は手動でも良いかもしれませんが翻訳作業をWeb上で簡単に行えるようにするためにTransifexなどを用意した方が良さそうですね

**Comment by Blue-Tone** [comment]
@mfmfuyu 「府内の最新感染動向」についてまだ未対応です。
Transifexについて、使用経験がないので、主導していただけると助かります。

**Comment by mfmfuyu** [comment]
@Blue-Tone 
ありがとうございます。
「府内の最新感染動向」についてはこちらで対応を行おうと思います。
Transifexについてですが、こちらで確認を行ってみようと思います。

**Comment by mfmfuyu** [comment]
大阪版では利用しない定義の整理なども行ったほうが良さそうですね

**Comment by teppei696** [comment]
マージ済みのため、クローズ
