### ISSUE TITLE
Transifex側で翻訳を行えるようにする

### ISSUE THREAD

**Issue by mfmfuyu** [codeforosaka/covid19#153]
親Issue : 多言語で表示できるようにしたい #110

## 改善詳細 / Details of Improvement
- 英語などの翻訳に関してはTransifexに誘導したい
- Transifex上で翻訳できるようにし、自動化も行いたい

### TODO
 - [x] Transifex上にプロジェクトを作成する
   - [x] 定義ファイルの同期ができている事を確認する
 - [x] [本家](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/TRANSLATION.md)を参考にTRANSLATION.mdを作成する

## 期待する見せ方・挙動 / Expected behavior
- Transifex側に誘導する
- Transifex上で翻訳できるようにする、自動化も行う。

**Comment by mfmfuyu** [comment]
Transifex側の自動更新が動作している事を確認しました、あとはTRANSLATION.mdを用意するだけかなと思っています。

**Comment by Blue-Tone** [comment]
こちら残件なければ、クローズしましょうか。

**Comment by mfmfuyu** [comment]
そうですね、問題なさそうなのでクローズします
