### ISSUE TITLE
いくつかの文言を本家と統一したい

### ISSUE THREAD

**Issue by mfmfuyu** [codeforosaka/covid19#154]
関連Issue : 多言語で表示できるようにしたい #110

## 改善詳細 / Details of Improvement
- 多言語化対応の作業中に気がついたのですが、本家と少しだけ違う文言がいくつかある
（例えば、「○○○　更新」 -> 「○○○　時点」など）
そこで、翻訳済みのリソースを流用できるように統一したい。

## 期待する見せ方・挙動 / Expected behavior
- 文言を本家と統一し、翻訳済みのリソースを流用する。

細かい文言の変更とはいえ、私の判断だけで変更は難しいと思いますのでご意見などをお伺いしたいと思います。

**Comment by teppei696** [comment]
こちら、まず経緯だけを説明すると
大阪版を構築する時に大阪府の方と話をする中で文言を細かく調整していった
※なので、基本的に本家版と文言が違うところは全て大阪府としての変更して欲しいという要望に沿ったものだと認識していただけると良いかと思います。
という経緯です。
ただ、合わせれるところはあわせたほうが東京側の翻訳リソースを有効活用できるというメリットは大きいと思うので、本家と違うところを洗い出して、合わせれるところがあれば合わせていくという動きをとっていきたいと思うのですがいかがでしょうか？

**Comment by mfmfuyu** [comment]
経緯に関してかしこまりました。
そうですね、合わせれるところがあれば合わせていくというのが一番の方法かなと私も思います。
文言については洗い出しを行おうと思います。

**Comment by mfmfuyu** [comment]
「大阪府の最新感染動向」のページ内だと、以下が東京版と違う文言になります。
左側が大阪版、右側が東京版になります。

- 陽性者の属性 -> 陽性患者の属性
- 陰性確認済（退院者累計） -> 陽性患者数
- 陰性確認済み（退院者累計） -> 退院
- 検査実施件数 ->検査実施人数(累計)
- ○○○ 時点 -> ○○○ 更新

**Comment by teppei696** [comment]
遅くなりましたが、大阪府の方と調整中の状況を共有いたします。
```
文言は担当部署が検討した結果で今の文言になっている。変更する場合、担当部署に確認が必要
```
ということでした。
結論が出るまで少し時間がかかりそうなのと、今この状況で実際に業務を行っている方々の時間をとるのは得策ではないかなーっと思っておりますが、いかがでしょうか？

**Comment by mfmfuyu** [comment]
文言の件、かしこまりました。
ありがとうございます。

私も得策ではないと思いますので本IssueをCloseし現状の文言で作業を進めていこうと思います。
