### ISSUE TITLE
属性情報に項番を追加したい

### ISSUE THREAD

**Issue by UedaShinichiro** [codeforosaka/covid19#161]
## 改善詳細 / Details of Improvement
陽性者の属性の各患者に対して、列：項番を追加したいです。
表示場所は列：日付の左側にお願いします。
なお、data.jsonの各患者情報の管理項目として”項番”を入力したものを用意してみました。
[data0330_項番あり.txt](https://github.com/codeforosaka/covid19/files/4401015/data0330_.txt)

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mfmfuyu** [comment]
こちら誰も対応していない状態でしたら私が対応しようと思います

**Comment by teppei696** [comment]
@mfmfuyu こちら大阪府からの要望なので、可能であれば急ぎ対応したいと思っております。
もし対応可能であればお願いしたいですー

**Comment by Yuukin256** [comment]
data.json を自動出力するスクリプト [y-chan/covid19osaka-scraping](https://github.com/y-chan/covid19osaka-scraping) は現状、 "No" という項目を付けて出力しています ([参考](https://github.com/y-chan/covid19osaka-scraping/blob/gh-pages/data.json))
自動化するスクリプトとの調整が必要かと思われます。

**Comment by mfmfuyu** [comment]
> @mfmfuyu こちら大阪府からの要望なので、可能であれば急ぎ対応したいと思っております。
> もし対応可能であればお願いしたいですー

こちら表示できるように対応を行いましたが、本日の更新分のデータには項番がないのですがどういたしましょうか？
データを拝見しましたが古いデータから順に番号を振っているようですので、合っていましたらindex値を利用すればいいのかなと思っています

**Comment by teppei696** [comment]
@mfmfuyu 
> こちら表示できるように対応を行いましたが、本日の更新分のデータには項番がないのですがどういたしましょうか？
こちら今日の最新版がdevelopmentにあがっているので、PG修正とともにdata.jsonにNoを付与したプルリクを投げていただけないでしょうか？
明日からはそのデータを元に大阪府の方にデータを修正していただけるように調整しようかと思います。

@UedaShinichiro 「項番」じゃなくて「No」でもよいですよね？

**Comment by UedaShinichiro** [comment]
Noというのはdata.jsonの項目名としてですか？それとも閲覧側に掲載する列名でしょうか？

**Comment by teppei696** [comment]
> Noというのはdata.jsonの項目名としてですか？それとも閲覧側に掲載する列名でしょうか？
data.jsonの項目名です
画面上の表示は「項番」でいこうと思います。

**Comment by UedaShinichiro** [comment]
了解です！問題ありません！明日からのデータ反映ではNoをdata.jsonに追加してプルリクしますね。

**Comment by mfmfuyu** [comment]
インデックスからではなく、`No`フィールドから番号を取得するように修正いたしましたので、こちらでPRを作成します。

**Comment by teppei696** [comment]
@UedaShinichiro @mfmfuyu こちら開発環境にデプロイしたので、ご確認をお願いします。
https://dev-covid19-osaka.netlify.com/

**Comment by mfmfuyu** [comment]
確認してみましたが問題ないかなと私は思います

**Comment by teppei696** [comment]
@mfmfuyu ありがとうございますー
大阪府のOKが出たらmasterにマージして本番にあげますー

**Comment by UedaShinichiro** [comment]
@teppei696 問題ないと思います。本番反映おねがいします！

**Comment by teppei696** [comment]
本番へのデプロイ実施中ですー
10〜15分経過したら本番に反映されると思いますー
