### ISSUE TITLE
「陽性者の属性」のソートにおける「未就学児」の位置

### ISSUE THREAD

**Issue by Yuukin256** [codeforosaka/covid19#167]
バグではなく、要修正です
## 起こっている問題 / The Problem
- 「陽性者の属性」を年代で昇順にソートすると「未就学児」が一番下になる

## 期待する見せ方・挙動 / Expected Behavior
- ソート時に10歳未満として扱う

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by ryo-is** [comment]
こちらのissueって対応されていますか？

**Comment by Yuukin256** [comment]
見対応です。よろしくお願いいたします。

**Comment by ryo-is** [comment]
承知いたしました。対応します。

**Comment by teppei696** [comment]
こちらSlackでも記載しましたが、「就学児」というデータも新たに追加されています。
ソートした時の並び順としては
「未就学児」「就学児」「10台」「20台」〜〜〜
という形になるかと思います。

**Comment by ryo-is** [comment]
承知いたしました。
仮に今後分類が増えても対応しやすいように実装していきます。

**Comment by ryo-is** [comment]
ちょっと今後どんな分類が増えるか想像できなくてその部分の実装ができてないのですが、一旦「未就学児」と「就学児」の位置がおかしいという件に対しては対応いたしました。
