### ISSUE TITLE
多言語化メニューの位置、UI改善

### ISSUE THREAD

**Issue by Blue-Tone** [codeforosaka/covid19#194]
関連Issue : #110 
ブランチ：[feature/issue-110-LauguageSelector](https://github.com/codeforosaka/covid19/tree/feature/issue-110-LauguageSelector)

## 改善詳細 / Details of Improvement
- [東京](https://stopcovid19.metro.tokyo.lg.jp/)に合わせて、上に移動する。
- サイドメニューの端に寄りすぎているので、隙間を開ける。
- フォントサイズを合わせる

該当ソース
components/SideNavigation.vue
```
      <div v-if="this.$i18n.locales.length > 1" class="SideNavigation-Language">
        <label class="SideNavigation-LanguageLabel" for="LanguageSelector">
          {{ $t('多言語対応選択メニュー') }}
        </label>
        <LanguageSelector />
      </div>
```

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Blue-Tone** [comment]
少しやろうとしましたが、きれいにできそうにないので諦めました。
CSSがあまり詳しくないので、どなたかお願いできますか？

**Comment by mosugi** [comment]
やりますー

**Comment by mosugi** [comment]
#198 でフォントサイズ以外対応しました。
feature/issue-110-LauguageSelector へのPRとしています。

フォントサイズはどのサイズに合わせればわかりませんでした。
#198にキャプチャがあるので、どのように変更すればよいかコメント頂けると助かります。

**Comment by Blue-Tone** [comment]
> #198 でフォントサイズ以外対応しました。
> feature/issue-110-LauguageSelector へのPRとしています。
> 
> フォントサイズはどのサイズに合わせればわかりませんでした。
> #198 にキャプチャがあるので、どのように変更すればよいかコメント頂けると助かります。

対応ありがとうございます！期待通りの表示です。
フォントサイズも現状で問題ありません。マージしました。

**Comment by mosugi** [comment]
確認ありがとうございますー！
