### ISSUE TITLE
英語翻訳グラフ「府民向けの相談窓口への相談件数」の修正について

### ISSUE THREAD

**Issue by open-osaka** [codeforosaka/covid19#216]
## 改善詳細 / Details of Improvement- 
英語訳グラフの項目を実績値(前日比)と重ならないようにしたい
## スクリーンショット / Screenshot
英語画面
https://www.dropbox.com/s/mhcxon3vj6we2dy/%E8%8B%B1%E8%A8%B3%E7%94%BB%E9%9D%A2.PNG?dl=0
![英語](https://user-images.githubusercontent.com/18328371/78859741-3b1bfa00-7a6b-11ea-8d49-b4cbc685ea3b.png)

日本語画面
https://www.dropbox.com/s/a4hke23awzkp35j/%E6%97%A5%E6%9C%AC%E8%AA%9E%E7%94%BB%E9%9D%A2.JPG?dl=0
![日本語](https://user-images.githubusercontent.com/18328371/78859752-440ccb80-7a6b-11ea-8c25-74f915c9c422.jpeg)

https://deploy-preview-206--rev-covid19-osaka.netlify.com/
## 期待する見せ方・挙動 / Expected behavior
グラフの項目を横長に変更し、実績値(前日比)と被らないようにする
## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer
レビューが確認できる所:https://deploy-preview-206--rev-covid19-osaka.netlify.com/
開発git:

**Comment by open-osaka** [comment]
開発githubが空欄でしたので追記しますhttps://github.com/codeforosaka/covid19/pull/206

**Comment by Blue-Tone** [comment]
#228 で修正してもらったのでクローズします。
