### ISSUE TITLE
20200409 data.json の更新不具合

### ISSUE THREAD

**Issue by Yuukin256** [codeforosaka/covid19#219]
## 起こっている問題 / The Problem
- [Googleドライブ](https://drive.google.com/drive/folders/15uhwuZEWLsltnLF197COJqSUWg8hu01a)に保存されているファイル patients_and_inspections.xlsx の 「【公開OK】コロナサイト用（日付ベース）」シートの日付が文字列の形式となっているので、変換スクリプトで処理できない

## 期待する見せ方・挙動 / Expected Behavior
- 日付の書式に変更する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Yuukin256** [comment]
@UedaShinichiro よろしくお願いいたします。

**Comment by UedaShinichiro** [comment]
@Yuukin256 ご指摘ありがとうございます。修正します。

**Comment by y-chan** [comment]
スクリプト側をどちらの書式でも対応できるように組み替えるのもありかもしれません。

**Comment by Yuukin256** [comment]
そもそもExcelファイルが先、スクリプト側が後発なので、後発のスクリプトに合うようにExcelを直してくれってお願いするのもおかしな話になりますよね。
@y-chan 仰る通り、"mm/dd"形式の文字列型からdatetime型への変換は今後2021年になった場合に対応しなければならないため可用性が下がってしまうんですよね…。やはり書式を統一するしか無いんでしょうね…。

**Comment by y-chan** [comment]
日付を読み込むためだけの関数を作って用意してみようかなと思ったんですがね...
文字列の場合は別の年に対応できない問題(名づけるなら2021年問題)が発生するので、割とExcel側をキッチリ修正するしか方法がないんですよね...

**Comment by UedaShinichiro** [comment]
@Yuukin256 いま修正版をGoogleドライブにあげました。18:00を過ぎてしまったので、手動で実行してもらえたりするでしょうか。すいません。

**Comment by y-chan** [comment]
ダメですね...
でもこれはスクリプト側で対応しましょうか...

![Screenshot_20200409-180714](https://user-images.githubusercontent.com/34832037/78878339-349e7a00-7a8d-11ea-988c-50d7d50c7647.png)

**Comment by UedaShinichiro** [comment]
@Yuukin256 すいません、もう一回だけアップしたのでお願いします。。

**Comment by Yuukin256** [comment]
@UedaShinichiro すいません、GitHub Actions の弱点として、予め手動実行が簡単にはできないんですよね。
@teppei678 もし19時より前にご確認いただけましたら、GutHub Actions のログ画面の右上の Re-run jobs で再実行をお願いします。
@y-chan そちらのログはおそらく18時の実行時なのでExcelファイルの更新前に実行したものと思われます。

**Comment by teppei696** [comment]
遅れました。いまからre-run jobsをやって見ます。

**Comment by y-chan** [comment]
@Yuukin256 失敗時は再実行できます。
これは私の元のリポジトリで再実行したGitHub Actionsのログですね。
先ほど更に再実行したところ、問題ないことを確認しました

**Comment by teppei696** [comment]
あ、re-run jobやってしまった。。。

**Comment by teppei696** [comment]
お、動いてプルリクあがってきた

**Comment by Yuukin256** [comment]
@y-chan 
> これは私の元のリポジトリで再実行したGitHub Actionsのログですね。

それは失礼いたしました。たしかによく見てみると actions の構造が違いますね。

@teppei696 早速の対応ありがとうございます。
