### ISSUE TITLE
「陽性者の属性」にて未翻訳の文字が存在する

### ISSUE THREAD

**Issue by teppei696** [codeforosaka/covid19#233]
## 起こっている問題 / The Problem
- 以下の文字が「陽性者の属性」にて未翻訳になっている
- 「就学児」（年代列）
- 「調査中」（居住地、年代、性別列）

## 期待する見せ方・挙動 / Expected Behavior
- それぞれの言語で翻訳された値になっている

## 起こっている問題の再現手段 / Steps to Reproduce
1. [レビュー環境](https://deploy-preview-218--rev-covid19-osaka.netlify.com/en)を開く
2. 「Details of patients testing positive」の中身を確認

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mfmfuyu** [comment]
こちら私の方で対応を行います

**Comment by teppei696** [comment]
こちら対応済みなので、クローズ
