### ISSUE TITLE
やさしい日本語訳のグラフの「全体累計」が訳されていない。

### ISSUE THREAD

**Issue by open-osaka** [codeforosaka/covid19#234]
## 起こっている問題 / The Problem
やさしい日本語訳の「新型コロナ受診相談センターへの相談件数」のグラフだけが「全体累計」が訳されていない。
## スクリーンショット / Screenshot
![全体累計がやさしい日本語訳できていないバグ](https://user-images.githubusercontent.com/24203651/79046571-bab4ef00-7c4c-11ea-8a0b-5d332bb53e06.JPG)
## 期待する見せ方・挙動 / Expected Behavior
「〇/〇までの全部」の表示になる
＜東京のサイト＞
![東京のサイト](https://user-images.githubusercontent.com/24203651/79046595-ee901480-7c4c-11ea-8488-b1029bbfc2d9.JPG)
＜翻訳登録画面＞
![翻訳登録画面](https://user-images.githubusercontent.com/24203651/79046617-0ebfd380-7c4d-11ea-87dc-08166a94f425.JPG)
## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer
確認できる画面：https://deploy-preview-218--rev-covid19-osaka.netlify.com/

**Comment by mfmfuyu** [comment]
こちら私の方で対応を行います

**Comment by mfmfuyu** [comment]
こちらのIssueですが、ローカル環境と[上記のURL](https://deploy-preview-218--rev-covid19-osaka.netlify.com/)を確認してみましたが問題なさそうでした
ブラウザのキャッシュが原因のような気がしますが、謎ですね...

**Comment by tuckya** [comment]
[上記のURL](https://deploy-preview-218--rev-covid19-osaka.netlify.com/) に macOS 上の Chrome からアクセスした場合 再現します。
グラフの種類を 「いちにちごと」から 「ぜんぶで」に切り替えると その時の表示が 「全体累計」となっています。

**Comment by mfmfuyu** [comment]
私の環境でも再現する事を確認いたしました、グラフの種類に関しては完全に見逃しておりました。
ありがとうございます。

**Comment by tuckya** [comment]
https://github.com/codeforosaka/covid19/blob/c8e6d0a7d5664952d89c6814bbe6ae1c1ed277fa/assets/locales/ja-Hira.json#L180
文字のスペースの有無だと思いますので 時間あれば 変更して Pullreq だします。

**Comment by mfmfuyu** [comment]
では、PRに関してはお願いしようと思います。
時間の関係上難しい場合は、ご連絡いただければ私の方で対応を行いますのでよろしくお願いいたします。

**Comment by tuckya** [comment]
transifex 側で `{date} の全体累計"` に対して 「英語」と「やさしいにほんご」 の翻訳行いました。

**Comment by mfmfuyu** [comment]
ありがとうございます、Transifex側にてレビューを行いました。
他の翻訳作業が残っていますので、変更がマージされるまでに少々お時間をいただくかもしれません。

**Comment by teppei696** [comment]
マージ済みのため、クローズ
