### ISSUE TITLE
検査陽性者の状況パネルへの補足追記

### ISSUE THREAD

**Issue by UedaShinichiro** [codeforosaka/covid19#239]
## 改善詳細 / Details of Improvement
検査陽性者の状況パネルに以下の補足を追記してもらえるでしょうか。
「※無症状・軽症には症状調査中を含む」

※陽性者の属性パネルと同じ位置に記載いただければ大丈夫です

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Yuukin256** [comment]
こちら対応します。

**Comment by Yuukin256** [comment]
@UedaShinichiro このような見た目で問題有りませんでしょうか。
![image](https://user-images.githubusercontent.com/52195426/79100389-52c3ed00-7da1-11ea-9490-47059e386777.png)

**Comment by UedaShinichiro** [comment]
@Yuukin256 ありがとうございます。すいません、逆でしたね。「軽症・無症状には～」でお願いします。掲載位置は問題ありません。

**Comment by Yuukin256** [comment]
@UedaShinichiro 文言修正してプルリク作りました。ご確認お願いたします。
