### ISSUE TITLE
やさしいにほんごの修正

### ISSUE THREAD

**Issue by teppei696** [codeforosaka/covid19#244]
## 改善詳細 / Details of Improvement
- やさしいにほんごの修正

## 期待する見せ方・挙動 / Expected behavior
- 以下に沿って修正できていること
[感染データやさしいにほんご国際確認.docx](https://github.com/codeforosaka/covid19/files/4469318/default.docx)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by teppei696** [comment]
こちらtransifex上で修正して、レビュー待ち状態にしてみましたが、、、
ここからどうしたらよいのやら・・・

**Comment by mfmfuyu** [comment]
こちら私の方でレビューを行いますので、少々お待ち下さい。
レビュー作業が終わり次第Transifexによって自動でPRが作成されますので、そちらをマージしていただければテスト環境に反映されるようになります。

**Comment by teppei696** [comment]
こちら反映済みなのでクローズ
