### ISSUE TITLE
最新のお知らせ欄の日付を非表示にする

### ISSUE THREAD

**Issue by UedaShinichiro** [codeforosaka/covid19#254]
## 改善詳細 / Details of Improvement
「2020/04/13 新型コロナウイルス関連の報道発表について（外部サイト） 」
と表示して貰っていますが、日付部分を表示しないようにすることは可能でしょうか。

（改修後）
「新型コロナウイルス関連の報道発表について（外部サイト）」

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Yuukin256** [comment]
@UedaShinichiro 日付部分を表示したく無い場合は news.json の日付部分を空白にして、日付が空白の場合は日付を表示しないようにする、という方法でいかがでしょうか。
日付をつけて表示したい情報が今後出た時に簡単に対応できる形にしたほうが良いと思います…。

**Comment by UedaShinichiro** [comment]
@Yuukin256 おっしゃる通りですね。日付けをつけて追加する場合もまだあると思いますので。それでお願いできますでしょうか。

**Comment by Yuukin256** [comment]
了解しましたー。対応します
