### ISSUE TITLE
やさしい日本語の追加対応

### ISSUE THREAD

**Issue by teppei696** [codeforosaka/covid19#258]
## 改善詳細 / Details of Improvement
- やさしい日本語を修正したい

## 期待する見せ方・挙動 / Expected behavior
- 以下の資料通りに翻訳されていること
[感染データ対訳やさしいにほんご.docx](https://github.com/codeforosaka/covid19/files/4491792/default.docx)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mfmfuyu** [comment]
こちら、頂いた資料を元に対応を進めていきます

**Comment by mfmfuyu** [comment]
こちら #271 で追加される補足用テキストを除き、Transifex上で翻訳作業を行いました、現在はレビュー待ちです
ですが、一点確認事項があります。

「当サイトについて」の「データについて」の部分なのですが、日本語だと「大阪府ホームページ」の後に「新型コロナウイルス感染症について」へのリンクがあるのですが、やさしい日本語の場合は該当する文言がなく、どこに入れるべきなのか分からない状態になっております。
こちらは日本語版と同じように「大阪府（おおさかふ）ホームページ」の後にリンクを追加すればよろしいのでしょうか？

**Comment by teppei696** [comment]
はい。それでお願いします。

**Comment by mfmfuyu** [comment]
そのように変更しました、ありがとうございます

**Comment by open-osaka** [comment]
大阪府からのデータで不具合を2か所発見したので、修理しました。
やさしい日本語のレビューお願いします。
403番目のデータ
修正前
　あさ9時（じ）から　よる6時（時）まで　電話（でんわ）できます。土曜日（どようび）、日曜日（にちようび）・休（やす）みも日（ひ）も電話（電話）できます。
修正後
　あさ9時（じ）から　よる6時（じ）まで　電話（でんわ）できます。土曜日（どようび）、日曜日（にちようび）・休（やす）みの日（ひ）も電話（でんわ）できます。

**Comment by mfmfuyu** [comment]
気が付きませんでした...問題ありませんでしたのでレビュー済みにしておきました。

**Comment by open-osaka** [comment]
ありがとうございます。

**Comment by open-osaka** [comment]
transifexに入りましたが、英訳のレビュー権限はありますが、やさしい日本語訳の権限がありません。何か手続きが必要ですか？

**Comment by mfmfuyu** [comment]
すみません、やさしい日本語の方のレビュー権限が上手く付与できていなかったようです。
お手数をおかけしますが、もう一度ご確認の方をよろしくお願いいたします。

**Comment by open-osaka** [comment]
レビュー終わりました😃

**Comment by teppei696** [comment]
PRあがってきていたのでマージしときました！

**Comment by teppei696** [comment]
マージ済みなのでクローズします。
