### ISSUE TITLE
英語版の追加対応

### ISSUE THREAD

**Issue by teppei696** [codeforosaka/covid19#263]
## 改善詳細 / Details of Improvement
- 英語版を修正したい

## 期待する見せ方・挙動 / Expected behavior
- 以下の資料通りに翻訳されていること
[修正反映-国際課記入EN-感染データ対訳英語版.docx](https://github.com/codeforosaka/covid19/files/4496020/-.EN-.docx)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mfmfuyu** [comment]
こちら、頂いた資料を元に対応を進めていきます

**Comment by mfmfuyu** [comment]
こちら #271 で追加される補足用テキストを除き、Transifex上で翻訳作業を行いました、現在はレビュー待ちです

**Comment by open-osaka** [comment]
翻訳お疲れ様です。よろしければTransfiexでレビューを行いますので、レビュー権限をお願いします。

**Comment by mfmfuyu** [comment]
レビュー権限の付与を行いました、ご確認よろしくお願いします。

**Comment by open-osaka** [comment]
ありがとうございます。今から確認作業を行います。

**Comment by open-osaka** [comment]
レビュー完了しました。

**Comment by mfmfuyu** [comment]
レビュー作業ありがとうございます！

**Comment by teppei696** [comment]
マージ済みです!

**Comment by teppei696** [comment]
マージ済みなので、クローズします。
