### ISSUE TITLE
検査陽性者の状況のデザイン／集計方法変更

### ISSUE THREAD

**Issue by teppei696** [codeforosaka/covid19#266]
## 改善詳細 / Details of Improvement
- 検査要請者の状況を変更したい

## 期待する見せ方・挙動 / Expected behavior
- 以下のように変更する
![image](https://user-images.githubusercontent.com/1694558/79630370-a06a9c00-818b-11ea-9b2a-30adff279cbd.png)
- データ取得元については要調整
- ただし、多言語化の本番反映が終わってから
- 参考サイト：http://www.pref.osaka.lg.jp/iryo/osakakansensho/corona.html

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mfmfuyu** [comment]
こちら多言語化の本番反映が終わり次第、私が対応したいと思います。

**Comment by mfmfuyu** [comment]
現状報告として、現在は以下のようにデザインの変更は対応が完了しております。
データの用意と翻訳の調整さえ終わってしまえば、本番にも取り込める状態にはなっております。

![image](https://user-images.githubusercontent.com/54523771/79981282-637e0c80-84df-11ea-83a7-c0efa3b24be9.png)

**Comment by teppei696** [comment]
こちらいったんプルリクをあげていただけないでしょうか？
それをベースにどこに何を入れるかを話ができればと思っております

**Comment by mfmfuyu** [comment]
今からチェックを行いました後にPRを作成いたします、少々お待ちください

**Comment by teppei696** [comment]
こちらですが、大阪府に確認していただいた結果を貼っておきます。

[20200424依頼事項整理版翻訳追記.txt](https://github.com/codeforosaka/covid19/files/4529175/20200424.txt)
[patients_and_inspections2.xlsx](https://github.com/codeforosaka/covid19/files/4529177/patients_and_inspections2.xlsx)

**Comment by teppei696** [comment]
以下の「検査陽性者の状況」に関係ないところは別のissueにしておきます。

```
■「陽性者の属性」
・項目名「退院」→「退院・解除」に修正
・自宅・宿泊療養解除は退院に含めるため、エクセルについては、今後、文字列で「解除」でカウントしてもらう。（今後、「自宅療養解除②」とかも出てくる）【伝達済】
・また、現在居住地に「大阪府大阪市」と表記しているが、「大阪府」を削除。【伝達済】

■「陰性確認済（退院者累計）」
標題の変更→「退院・解除済累計」
```

**Comment by mfmfuyu** [comment]
大阪府からいただきました、文言の変更などに対応いたしました。
集計方法の変更も私の方で対応を行おうと思います。

**Comment by teppei696** [comment]
お願いします！

**Comment by mfmfuyu** [comment]
スクリプト側の調整も行い、PRを作成しました #338 
`patients_and_inspections2.xlsx`を参考に`ピポット集計`のシートから療養者の情報を取得するようにしているのですが、現在ドライブにアップロードされているファイルにはそれがない状態なのですが、今後の更新から追加されるという認識であっていますでしょうか？

**Comment by mfmfuyu** [comment]
![image](https://user-images.githubusercontent.com/54523771/80300196-7a6d7900-87d5-11ea-8508-7fd2386e30e0.png)
フロント側を新データに対応するように変更しました。
`現在陽性者数`の数値に関しては`入院`などの数値をすべて足した物になります。

**Comment by mfmfuyu** [comment]
また、デザインの変更・項目の追加に伴い`aria-label`の変更が必要だと思いますので
```
検査陽性者の状況: 検査実施人数は***人、うち累積の陽性者数は***人です。入院中は***人で、うち軽症・中等症は***人、また重症は***人です。さらに死亡は***人、退院は***人です。
```
から
```
検査陽性者の状況: 検査実施人数は***人、うち累積の陽性者数は***人で、現在陽性者数は***人です。入院中は***人で、重症は***人です、また入院調整中は***人です。自宅療養は***人、宿泊療養は***人、また療養等調整中は***人です。さらに死亡は***人、退院・解除済累計は***人です。
```
に変更しようと思うのですが、こちら大丈夫でしょうか？

**Comment by teppei696** [comment]
@mfmfuyu 
はい。上記で問題ないと思いますので修正をお願いできますでしょうか？

**Comment by teppei696** [comment]
入院中のデータが入院中＋入院調整中になってデータが変になっているので対応しますー

**Comment by teppei696** [comment]
マージ済み＋翻訳済みなのでクローズ
