### ISSUE TITLE
陽性者の属性

### ISSUE THREAD

**Issue by teppei696** [codeforosaka/covid19#267]
## 改善詳細 / Details of Improvement
- 陽性者の属性の「居住地」の表記変更

## 期待する見せ方・挙動 / Expected behavior
- 以下のように修正
  - [x] 項目名「退院」→「退院・解除」に修正
    - [x] 翻訳（やさしい日本語）：「退院・解除」→　病気（びょうき）が　なおった
    - [x] 翻訳（英語）：Discharged from hospitals/home recuperation/special facilities.
  - [x] 自宅・宿泊療養解除は退院に含めるため、エクセルについては、今後、文字列で「解除」でカウントしてもらう。（今後、「自宅療養解除②」とかも出てくる）【伝達済】 
  - [x] また、現在居住地に「大阪府大阪市」と表記しているが、「大阪府」を削除。【伝達済】
    - [x] 翻訳が必要
- ついでに
  - 「陰性確認済（退院者累計）」
    - [x] 標題の変更→「退院・解除済累計」
      - [x] 「退院・解除済累計」 → 病気（びょうき）が　なおった　人（ひと）の　かず 
      - [x] 「退院・解除済累計」 → Accumulated number of people discharged from hospitals/home recuperation/special facilities.

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Yuukin256** [comment]
- 項目名「退院」→「退院・解除」に修正
- 現在居住地に「大阪府大阪市」と表記しているが、「大阪府」を削除
- 「陰性確認済（退院者累計）」 標題の変更→「退院・解除済累計」

について対応します

**Comment by Yuukin256** [comment]
- 「陰性確認済（退院者累計）」 標題の変更→「退院・解除済累計」

についてはパネル標題のみ対応しています。
「検査陽性者の状況」内については触っていません

**Comment by teppei696** [comment]
対応ありがとうございます。
翻訳するためにも一旦マージします！

**Comment by teppei696** [comment]
こちらmerge済み＋翻訳済みなのでクローズ
