### ISSUE TITLE
陽性者の属性の「退院」列で「○」扱いするデータの追加

### ISSUE THREAD

**Issue by teppei696** [codeforosaka/covid19#268]
## 改善詳細 / Details of Improvement
- 陽性者の属性の「退院」列で「○」扱いするデータを追加したい

## 期待する見せ方・挙動 / Expected behavior
- patients_and_inspectionsの「【公開OK】府HP用(陽性者ベース)」シートの「入退院の状況」（H列）に値が追加されているため、サイト上で「○」と変換するものを追加したい
  - 死亡退院→○
  - 自宅療養→○
  - 宿泊療養→○
  - 退院→○
  - 入院中→（空白）
  - 入院調整中（空白）

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by teppei696** [comment]
修正可能

**Comment by Yuukin256** [comment]
こちら対応します
