### ISSUE TITLE
翻訳の修正

### ISSUE THREAD

**Issue by teppei696** [codeforosaka/covid19#304]
## 改善詳細 / Details of Improvement
- 翻訳を修正して欲しい

## 期待する見せ方・挙動 / Expected behavior
- 以下の通りに修正する
  - [ ] やさしいにほんご：「感染経路不明」にフォーカスを当てた際に、文字が長いので切れる
    - （スラッシュで折り返せたらいいものの、本日時点ではやむなし？）
  - やさしいにほんごの新たな修正　（こちらは間に合えばでかまいません）
    - [x] 「免責事項（大阪府（おおさかふ）の 責任（せきにん））」の部分は、「大阪府（おおさかふ）の 責任（せきにん）」のみ記載。（免責事項のルビを記載すると、タイトルが長くなるため）
    - [x] 「といあわせさき （こまった ときに 聞（き）くところ）」についても、「といあわせさき」は削除し、「こまった ときに 聞（き）くところ」のみ記載。
    - [x] 問い合わせ先の電話番号について、ぽつ１つ目と２つ目の電話番号の記載が半角と全角でそろっていないため、記載をそろえる。（半角で統一）
    - [x] 問い合わせ先のぽつ１つ目の記載で、あさ9時（じ）から　よる6時（じ）までの部分を、午前（ごぜん）9時（じ）から　午後（ごご）6時（じ）までに変更。
  - 英語版の修正
    - [x] お問い合わせ先に、「」が残っているため、””に修正。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Yuukin256** [comment]
- やさしいにほんご：「感染経路不明」にフォーカスを当てた際に、文字が長いので切れる

を修正しますー
