### ISSUE TITLE
英語/やさしいにほんごの表示において文章や単語の見切れがある

### ISSUE THREAD

**Issue by aktuehr** [codeforosaka/covid19#310]
## 起こっている問題 / The Problem
- 英語表示/やさしいにほんごの表示において、見切れが発生している箇所がある

### 英語(横幅320px)
![スクリーンショット 2020-04-23 8 29 34](https://user-images.githubusercontent.com/30136823/80043616-2cd6df00-853d-11ea-99a1-160552d53b9d.png)
![スクリーンショット 2020-04-23 8 29 54](https://user-images.githubusercontent.com/30136823/80043621-2fd1cf80-853d-11ea-9e5e-a1a20b4e97af.png)
![スクリーンショット 2020-04-23 8 30 04](https://user-images.githubusercontent.com/30136823/80043622-306a6600-853d-11ea-9bfa-7f512c9e7598.png)
![スクリーンショット 2020-04-23 8 32 39](https://user-images.githubusercontent.com/30136823/80043623-3102fc80-853d-11ea-9f3b-f2a01a95935c.png)
![スクリーンショット 2020-04-23 8 32 51](https://user-images.githubusercontent.com/30136823/80043629-32ccc000-853d-11ea-8b24-d894de05573c.png)
![スクリーンショット 2020-04-23 8 33 01](https://user-images.githubusercontent.com/30136823/80043630-32ccc000-853d-11ea-857c-8385b7779edb.png)

### やさしいにほんご(横幅320px)
![スクリーンショット 2020-04-23 8 27 41](https://user-images.githubusercontent.com/30136823/80043650-45df9000-853d-11ea-889b-1628e41a776d.png)
![スクリーンショット 2020-04-23 8 27 59](https://user-images.githubusercontent.com/30136823/80043653-4710bd00-853d-11ea-8b75-169335820c25.png)
![スクリーンショット 2020-04-23 8 28 15](https://user-images.githubusercontent.com/30136823/80043655-4841ea00-853d-11ea-8877-7c2f96efd3bb.png)
![スクリーンショット 2020-04-23 8 28 23](https://user-images.githubusercontent.com/30136823/80043658-48da8080-853d-11ea-9fb7-07df399e7e7f.png)
![スクリーンショット 2020-04-23 8 28 52](https://user-images.githubusercontent.com/30136823/80043661-49731700-853d-11ea-9ff4-0d0761b218c9.png)
![スクリーンショット 2020-04-23 8 29 01](https://user-images.githubusercontent.com/30136823/80043662-4a0bad80-853d-11ea-908b-fbabcd949d65.png)
![スクリーンショット 2020-04-23 8 28 32](https://user-images.githubusercontent.com/30136823/80043659-48da8080-853d-11ea-8a9c-cd8f0a5bdd19.png)

## 期待する見せ方・挙動 / Expected Behavior
- 表示幅に依らず、文字の見切れが発生しない
    - 段落ちするか、横にスクロールできるようにする

## 起こっている問題の再現手段 / Steps to Reproduce
1. スマートフォンなど横幅が狭い端末で、 https://covid19-osaka.info/ を閲覧する
2. 言語選択メニューより「英語」もしくは「やさしいにほんご」を選択する
3. 各種項目の表示内容のうち見切れが発生しているものがある

## 動作環境・ブラウザ / Environment
- 私が確認した動作環境は以下です
  - macOS(10.15.3) / Chrome(80.0.3987.163), Safari(13.0.5)
  - Android(10)<Pixel 3a> / Chrome(81.0.4044.111)
  - iPadOS(13.3.1) / Sarari, Chrome(80.0.3987.95)

**Comment by teppei696** [comment]
対応済のため、クローズ
