### ISSUE TITLE
Excelからdata.jsonを出力できるようにする

### ISSUE THREAD

**Issue by teppei696** [codeforosaka/covid19#32]
## 改善詳細 / Details of Improvement
- Excelからdata.jsonを出力できるようにする

## 期待する見せ方・挙動 / Expected behavior
- コンバーターphpでexcelからdata.jsonを出力できるようにする
- ファイルは
- [①検査件数等.xlsx](https://github.com/codeforosaka/covid19/files/4336742/default.xlsx)
- [②陽性者情報.xlsx](https://github.com/codeforosaka/covid19/files/4336743/default.xlsx)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by y-chan** [comment]
こんばんは、兵庫県版にてデータ関連の修正/作成の自動化を行っていた者です。
大阪府版の現状はわからないのですが、府内の高校に通っているため貢献させていただければと思います。
data.jsonを出力するためにいろいろデータが足りない(テキストデータを抽出できるのはWordファイルのみ...?)ようですが、今後どのような形で動いていくのでしょうか。
教えていただければ幸いです。

**Comment by teppei696** [comment]
@y-chan リアクションが遅くなって申し訳ありません。
今後の方針としては大阪府より一覧形式のExcelをいただくことになっており、それを元に自動出力しようと思っております。
https://github.com/codeforosaka/covid19/blob/development/tool/convert.php
に手を加えていくことになりそうです。
Excelが入手できたらまた共有する予定です。

**Comment by teppei696** [comment]
ファイルはこちらですね。
[①検査件数等.xlsx](https://github.com/codeforosaka/covid19/files/4336742/default.xlsx)
[②陽性者情報.xlsx](https://github.com/codeforosaka/covid19/files/4336743/default.xlsx)
これらを元にdata.jsonの一部を自動で出力できるといいなーっと思っています。

**Comment by teppei696** [comment]
@y-chan 
とりいそぎ、03/15迄の分は私が手作業でdata.jsonを作ろうとしているので可能であればこのissueをとってもらえると嬉しかったりするのですが、いかがでしょうか？

**Comment by y-chan** [comment]
わかりました、私はPythonで作業しているのですが、それで大丈夫であれば今から対応したいと思います

**Comment by teppei696** [comment]
ありがとうございます。pythonで大丈夫です！お願いします！

**Comment by y-chan** [comment]
現在いいところまで作成できているのですが #38 を見て、これも取り込んでしまおうと考えているのですが、大丈夫でしょうか?

**Comment by teppei696** [comment]
返事が遅れて申し訳ありません。
実は他にも府の方に出して欲しいと言われているグラフがあり、それらの元データを自動出力する対応は別issueかなっと思っていました。
あと、#38 はどうやって出すかは府の人に確認中なので、一旦今のissueを終わらせていただいたほうがよいかと思っています。

**Comment by teppei696** [comment]
今②の方と話をして②のExcelから出力し、「検査陽性者数の「退院」」の数を日毎に集計してくれという回答がありました。
もし対応可能であれば、取り込んでいただけると嬉しいです。
※今から#38の対応を私が実施するので、一旦手での作成は実施していきます。
名前的には「treated__summary」ですかね。

**Comment by y-chan** [comment]
了解しました、対応できそうなので取り込みます。

**Comment by y-chan** [comment]
出来上がりました。
https://github.com/y-chan/covid19osaka-scraping
相談件数等は解析できるExcelデータ等がないため、現状は作らない仕様にしています。

**Comment by teppei696** [comment]
@y-chan 
ようやく手が空いたので作っていただいたものを見させていただきます

**Comment by teppei696** [comment]
@y-chan 
すいません。ようやく見始めれたのですが、
「requirements.txt」ってGithubにあげてもらってよいでしょうか？

**Comment by y-chan** [comment]
すみません、上げ忘れていました...
今上げましたのでご確認ください...

**Comment by teppei696** [comment]
ありがとうございます。確認します。

**Comment by teppei696** [comment]
こちら出力できることを確認できました！
細かいところで修正したほうがよいかなーっと思うところがあり、プルリクでやり取りさせてもらえると嬉しいのですが、
私にてこのリポジトリにプルリクなげたほうがよいですかね？
それとも @y-chan さんがなげますか？

**Comment by y-chan** [comment]
プルリクなげてもらえると助かります！

**Comment by teppei696** [comment]
承知しましたー
明日になりますが投げておきます

**Comment by Blue-Tone** [comment]
こちら見てみます。

[slackスレッド](https://code-for-osaka.slack.com/archives/CVCF09HV0/p1584962604011600)
以下転記：
自動化について現状をまとめますね。
今は大阪府の方にプルリクを投げてもらってそれを僕がマージするっていう流れです（だいたい1日1回）
元データとしては添付する4つです。このExcelを元に大阪府の方にデータを作ってプルリクを投げてもらっています。
で、ここからどう自動化するかですが、ExcelをGoogleドライブでもどこでも良いのであげてもらって、Github Actionでなんとかdata.jsonを自動生成できないかなーっと思っています。
※①②を元にdata.jsonを作るpythonは[こちらのcovid19osaka-scraping](https://github.com/y-chan/covid19osaka-scraping)で作ってもらっている状況です。

**Comment by y-chan** [comment]
@Blue-Tone 現状はslackでディスカッションされているのでしょうか。
問題なければどなたかに招待いただけると嬉しいのですが...

**Comment by Blue-Tone** [comment]
@y-chan 
はい。少し前にSlackが立ち上がったようです。
こちらの招待リンクから登録お願いします。
https://join.slack.com/t/code-for-osaka/shared_invite/zt-cwdlx5l0-HKsLn6CVzw8XPBVRFRzDHg

**Comment by Blue-Tone** [comment]
GoogleDriveに格納して、GithubActionsでDL、変換実行までできた。

- 実装中のコード
https://github.com/Blue-Tone/covid19osaka-scraping/pull/1

- ファイル置き場
（GoogleDriveで共有設定。GoogleDriveのフォルダの設定で「アップロードしたファイルを変換する」をオフにする。）
https://drive.google.com/drive/u/0/folders/16mJ8dLE1a0hIFYX35MH28xTiUEkqiDWC

# TODO

- [ ] 作成したdatta.jsonを取得できるようにする。
[アーティファクトを使用してワークフローデータを永続化する](https://help.github.com/ja/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts)
- [ ] readmeの改定

**Comment by y-chan** [comment]
生成したjsonの生成はGitHub Pagesを使うことで実現出来るはずです。
Google Driveで管理することが決定しているならば、他のデータに関しても生成できるよう調整します。

**Comment by Blue-Tone** [comment]
@y-chan コメントありがとうございます。
GitHub Pages、他のデータ生成、お願いできると助かります。
一旦、PRしておきますね。

**Comment by Blue-Tone** [comment]
@y-chan
アーティファクトを試してみたら、data.jsonを取得できるようにできました。
まだGithub Pagesの作業をしていなかったら、こちらの仕組みをPRしますがいかがでしょうか？

Github Actionの右上の「Artifacts 1」のリンクからDLできるようになります。
https://github.com/Blue-Tone/covid19osaka-scraping/pull/2/checks?check_run_id=529520256

**Comment by y-chan** [comment]
@Blue-Tone 申し訳ないですが、既にGitHub Pagesブランチへのアップロード、問い合わせデータの変換スクリプトの追記まで完了済みです...
https://github.com/y-chan/covid19osaka-scraping/blob/gh-pages/
まだGitHub Pagesを有効化して間もないのでPagesの方には反映されていませんが、現状はこれですべてのデータが取り出せるようになっているはずです。

**Comment by Blue-Tone** [comment]
了解です。
では、その方針でいきましょう！

**Comment by y-chan** [comment]
Google Driveのデータを使用させていただいていますが、最新のものではないようなので、生成されるデータは古いままになっています。
もし、このまま私のスクリプトを使用していただく方針で決定するのであれば、そちらの方で適宜Excelファイルを更新していただくようにお願いしたいと思います。

**Comment by Blue-Tone** [comment]
@teppei696 
自動で
[Google Drive](https://drive.google.com/open?id=1n0ukO1gPiG5etAwDjzVYzPk-2OIbwE02)に元データを格納する。

元データ:
- ①検査件数等.xlsx
- ②陽性者情報.xlsx

**Comment by y-chan** [comment]
先ほど書きましたが、
③府民向け相談窓口相談件数.xlsx
④新型コロナ受診相談センター帰国者接触者相談センター相談件数.xlsx
に関しても自動化できましたので、全ファイルのアップデートを私からもお願いします。

**Comment by UedaShinichiro** [comment]
@teppei696 
3/24本日受領しているファイルを共有させて貰います。
なお、最終更新日や時点日付関係はエクセルに記載がなく、現在は手入力していますが、本エクセルに入力場所を用意すれば、そこから吸い上げて貰うことも可能でしょうか？

[20200324（①検査件数等②陽性者情報）R0203182330.xlsx](https://github.com/codeforosaka/covid19/files/4374209/20200324.R0203182330.xlsx)
[20200324③府民向け相談窓口相談件数.xlsx](https://github.com/codeforosaka/covid19/files/4374210/20200324.xlsx)
[20200324④新型コロナ受診相談センター（帰国者・接触者相談センター）相談件数.xlsx](https://github.com/codeforosaka/covid19/files/4374211/20200324.xlsx)

**Comment by y-chan** [comment]
@UedaShinichiro 
記載されている場所が決まっていれば吸い上げられます。

**Comment by UedaShinichiro** [comment]
@y-chan 
了解です。ファイル作成元と調整してみます。

**Comment by y-chan** [comment]
@UedaShinichiro あと、今まで私が入手していたファイルと今回ここにアップロードしていただいたファイルとでデータの形式が違うので、出来れば統一するようお願いします。

**Comment by teppei696** [comment]
@y-chan @UedaShinichiro 
ファイルフォーマットも大阪府で随時少しずつ更新されてきたのが現状だと思っています。
今あがっているファイルを正として今後進めていければと思っているのですがいかがでしょうか？
※もう少しフォーマットが変わりそうであれば、それをまって最終版としたいです。

**Comment by UedaShinichiro** [comment]
@y-chan 
ですよね。。今後は形式を変えないようにお願いしておきます。
また、時点日付の吸出しについては、各シート（ピボット集計シートを除く）のA1列を専用の枠として使いたい旨、先方にお願いしました。明日受領分で提示させて貰います。

これとは別に、最終更新（lastUpdate）だけは作成いただいているプログラムを実行した日付を設定してもらうことは可能ですか？

**Comment by y-chan** [comment]
@teppei696 そうですね、現状とは違うようになったとしても、最終的に型を決めていただければ良いと思っています。
とりあえずは今回頂いたExcelファイルに合わせる形でスクリプトに変更を加えていきます。

**Comment by y-chan** [comment]
@Uedashinichiro
> lastUpdateのみプログラムの実行時
可能です、そのつもりでいます。

**Comment by UedaShinichiro** [comment]
@y-chan 想定されていたどおりでよかったです。よろしくお願いします。

**Comment by y-chan** [comment]
新しいフォーマットでの生成に対応するため、更新を行い、無事に全データが問題なく吐き出せることが確認できました。
あとは、更新日時等がExcelファイルに記載されるようになれば、それを取得するように変更を加えれば多分完璧です。

**Comment by UedaShinichiro** [comment]
本日受領データを共有します。A１を時点日付にしてもらいました。
①検査件数等②陽性者情報について、ピポッド集計シートは項目の入れ替えが入っています。
以後、入れ替えないように先方にはお願いしています。
申し訳ないのですが、この内容で最終調整していただけるでしょうか。

[20200324（①検査件数等②陽性者情報）R0203182330.xlsx](https://github.com/codeforosaka/covid19/files/4380025/20200324.R0203182330.xlsx)
[20200324③府民向け相談窓口相談件数.xlsx](https://github.com/codeforosaka/covid19/files/4380026/20200324.xlsx)
[20200324④新型コロナ受診相談センター（帰国者・接触者相談センター）相談件数.xlsx](https://github.com/codeforosaka/covid19/files/4380027/20200324.xlsx)

**Comment by teppei696** [comment]
今の状況的には
GoogleドライブにおいたファイルをGithub Actionで変換かけてdata.jsonを作成（最終のフォーマット修正には未対応）までできている感じですかね？
※この辺の状況確認ってここでやったほうがよいのか、Slackでやったほうがよいのか・・・

これって最終的にはこのリポジトリのdevelopmentブランチにpushできると最高だなーって思っているのですが、それは難しいですかね？

**Comment by y-chan** [comment]
現状はここにアップロードしているファイルを直接取得しているので、Google Driveにあげるところはやっていません。(誰が、どのドライブを使って共有するか未決定だからです。)

自動プッシュはできます。(兵庫県版ではPRにしていますが、以前は自動プッシュしていたことがあります。)

**Comment by teppei696** [comment]
@y-chan 共有ありがとうございます！
どこにおくのか（誰のGoogle Drive使うのか）はおいてくれる人（大阪府）の人と調整していきますー

**Comment by y-chan** [comment]
@UedaShinichiro Excelファイルを上げ間違えているようですー
頂いたデータは昨日頂いたものと同一のもののようです

**Comment by teppei696** [comment]
一旦置く場所を作って大阪府の方にも共有をしました。
※各種手続きがあるので実際に運用開始できるのはもう少し時間がかかりそうですが・・・
https://drive.google.com/drive/folders/15uhwuZEWLsltnLF197COJqSUWg8hu01a?usp=sharing
ここにおいたデータを元にdevelopmentブランチのdata.jsonにpushできると最高ですね。
※アクセス権限どうしようかな・・・

**Comment by teppei696** [comment]
ごめんなさい。Googleドライブはもうちょっと調整がいりそうなので、お待ち下さい。

**Comment by UedaShinichiro** [comment]
> 本日受領データを共有します。A１を時点日付にしてもらいました。
> ①検査件数等②陽性者情報について、ピポッド集計シートは項目の入れ替えが入っています。
> 以後、入れ替えないように先方にはお願いしています。
> 申し訳ないのですが、この内容で最終調整していただけるでしょうか

すいません。。03/25受領データは以下のものに差替お願いします。

[20200325（①検査件数等②陽性者情報）R0203182330.xlsx](https://github.com/codeforosaka/covid19/files/4384394/20200325.R0203182330.xlsx)
[20200325③府民向け相談窓口相談件数.xlsx](https://github.com/codeforosaka/covid19/files/4384395/20200325.xlsx)
[20200325④新型コロナ受診相談センター（帰国者・接触者相談センター）相談件数.xlsx](https://github.com/codeforosaka/covid19/files/4384397/20200325.xlsx)

**Comment by UedaShinichiro** [comment]
03/26受領データも共有します。

[20200326（①検査件数等②陽性者情報）R0203182330.xlsx](https://github.com/codeforosaka/covid19/files/4386270/20200326.R0203182330.xlsx)
[20200326③府民向け相談窓口相談件数.xlsx](https://github.com/codeforosaka/covid19/files/4386271/20200326.xlsx)
[20200326④新型コロナ受診相談センター（帰国者・接触者相談センター）相談件数.xlsx](https://github.com/codeforosaka/covid19/files/4386273/20200326.xlsx)

**Comment by teppei696** [comment]
共有フォルダを作ってそこに共有してもらったファイルを配置しました。
https://drive.google.com/drive/folders/15uhwuZEWLsltnLF197COJqSUWg8hu01a?usp=sharing
※ここにGithub Action経由でアクセスして、data.jsonを作って、developmentブランチにpushできたら最高ですね。

ただ、「ファイル名」は決めないとですね。

**Comment by y-chan** [comment]
そうですね...
こちらとしては、Google Driveからダウンロードする際のURLさえ変わらなければいい訳なんですが、ファイル名が変わると共有URLも変わってしまうので、一定の名前を決める必要がありますね...。

**Comment by y-chan** [comment]
参考までに、スクリプト内でダウンロードする際は1,2のまとめファイルを"patients_and_inspections.xlsx"、3を"contacts1.xlsx"、4を"contacts2.xlsx"として保存させています。

**Comment by teppei696** [comment]
なるほど。
ファイル名は固定にしといて、毎日上書きしてもらえるとダウンロードURLが固定にできていいよねって感じですね。
その方向で調整します。
とりあえず、googleドライブ内のファイル名は揃えておきました。

**Comment by y-chan** [comment]
了解です、ありがとうございます。

**Comment by y-chan** [comment]
最新の形式に対応させて、なおかつ正式なリンクに切り替えました。
https://github.com/y-chan/covid19osaka-scraping

**Comment by y-chan** [comment]
#160 と #161 のデータ側(スクリプト側)の対応を後で行おうと思います。
とりあえずはUI側の調整は他の方にお願いしたいと思います。(手が開けばやります)

**Comment by teppei696** [comment]
@UedaShinichiro 
今日更新したデータの元になるExcelを共有いただくことは可能でしょうか？

@y-chan 
最新のExcelを元に稼働確認を実施していきたいのですが、Google Driveにおいたら定期的に動いているGithub Actionからとりにきて、developmentにpushされるという認識でよいでしょうか？

**Comment by y-chan** [comment]
@teppei696
いいえ、[私のリポジトリ](https://github.com/y-chan/covid19osaka-scraping)のgh-pagesブランチにプッシュされます。
なので、自動化する場合はこちらをプルしてdataディレクトリにプッシュする形のGitHub Actionsをこのcovid19リポジトリに組み込む必要があります。

**Comment by teppei696** [comment]
@y-chan 承知しましたー
さっきExcelを最新化したので、15分後ぐらいに「covid19osaka-scraping」のgh-pageブランチのdata.jsonが更新されるはずなので、それとこのリポジトリのdata.jsonを比較して、いけそうなら僕がプルリクをなげますー（前回はプルリク作れなかったので今度こそはがんばります）

**Comment by Yuukin256** [comment]
"【公開OK】ピポット集計" シート症状欄の入力位置が以前より1行下にずれてるようで、Giuhub Actions がエラー吐いています。
スクリプトが新しい構成のファイルに対応するようにした修正版を作成し、プルリクを投げました。
y-chan/covid19osaka-scraping#2

**Comment by teppei696** [comment]
上記も反映したソースをプルリクとしてあげましたが、
1点だけ問題があって、日付を
```
"date": "2020\/03\/30 20:50"
```
という今のdata.jsonにあわせる形に出力したいのですが、僕の力量ではなぜかバックスラッシュが「\\」2つ重なって出力されてしまい。。。

誰か詳しい人教えてください。。。
```
self.patients_sheet.cell(row=1, column=1).value.strftime("%Y/%m/%d %H:%M")
```

**Comment by y-chan** [comment]
先程頂いたPRをマージしました。ご協力ありがとうございます。

`\/`が`\\/`になってしまう件に関しては私も直し方がよくわかっておらず、現状兵庫県版では`/`でも特に問題なく動作しているため、このまま出力させています。

**Comment by teppei696** [comment]
そうなんですね。バックスラッシュなしだと僕の開発環境だと動かなかったのですが、そっちを修正するようにしてみます！
あとは自動出力するといまのdata.jsonと差分が見つかったのでエクセルが間違えているのかどうかを確認してみます

**Comment by UedaShinichiro** [comment]
@teppei696 本日反映済のファイルを共有します。
[20200331（①検査件数等②陽性者情報）R0203182330.xlsx](https://github.com/codeforosaka/covid19/files/4414704/20200331.R0203182330.xlsx)
[20200331③府民向け相談窓口相談件数.xlsx](https://github.com/codeforosaka/covid19/files/4414705/20200331.xlsx)
[20200331④新型コロナ受診相談センター（帰国者・接触者相談センター）相談件数.xlsx](https://github.com/codeforosaka/covid19/files/4414706/20200331.xlsx)

**Comment by teppei696** [comment]
@UedaShinichiro ありがとうございます。
なんか書式が少しずつ変わってうまく自動抽出ツールが動かない・・・

**Comment by teppei696** [comment]
@UedaShinichiro なんとか動くようにはできたのですが、次にExcelから自動出力したデータと今の本番のデータで以下が異なっているのですが、本番のデータが正で良いですかね？

```
項番：198の性別が
　本番：男性
　自動出力：女性
項番：195の性別が
　本番：男性
　自動出力：女性
項番：59の退院が
　本番：空白
　自動出力：○
項番：58の退院が
　本番：空白
　自動出力：○
```

**Comment by teppei696** [comment]
ちなみに今回Excelからの自動出力で問題がおきた箇所
・日付を入力しているところの書式が「文字列」になっていた
・データがないのに日付が入っていたので空のデータができた

**Comment by y-chan** [comment]
書式をコロコロ変えられるとスクリプトの対応が大変なので統一してもらった方がいい、と言うよりは統一してもらわないと困る、という感じですね...
府と連携しているなら尚更、なんですけども...

**Comment by teppei696** [comment]
明日は元エクセルをもらってそれで僕の環境で自動出力したものでプルリク投げてみようと思います。
その時に細かい注意事項を洗い出してお伝えする感じでいこうかと思っております

**Comment by UedaShinichiro** [comment]
> @UedaShinichiro なんとか動くようにはできたのですが、次にExcelから自動出力したデータと今の本番のデータで以下が異なっているのですが、本番のデータが正で良いですかね？
> 
> ```
> 項番：198の性別が
> 　本番：男性
> 　自動出力：女性
> 項番：195の性別が
> 　本番：男性
> 　自動出力：女性
> 項番：59の退院が
> 　本番：空白
> 　自動出力：○
> 項番：58の退院が
> 　本番：空白
> 　自動出力：○
> ```

@teppei696     私のミスですね。自動出力があってます。訂正のプルリク投げても良いでしょうか？

**Comment by teppei696** [comment]
はい。プルリクお願いします。
ただ、現在布団の中なので、早くとも明日朝一になるかと

**Comment by UedaShinichiro** [comment]
@teppei696 夜分にすいません。了解です。プルリクしたのでまた明日お願いします。（報道発表の追加分も入れました）

**Comment by y-chan** [comment]
知らない間に私のスクリプトがこのリポジトリに取り込まれているのですが、MITで公開しているので問題はないものの、断りは入れておいてほしかったです...

**Comment by Yuukin256** [comment]
@y-chan マージして取り込めばいずれにせよライセンス上の問題は発生しないであろう、という事ばかりに目を向けてしまいました。スクリプトを作成してくださっている事に対する敬意を失念していたことお詫びします。現在の状態に差し支えありませんでしたら、追認いただけますと幸いです。

**Comment by teppei696** [comment]
@y-chan 申し訳ありません。
確かに何も話をできておりませんでした。
以後、このようなことがないように気をつけます

**Comment by y-chan** [comment]
@teppei696 @Yuukin256 
断りがなかったのは少し不満なものの、今問題なくデータ更新が出来ているのであれば特に問題はありません。今は最新情報を確実に伝えるように体制を整える方が重要でしょうから...

今後は気をつけていただければと思います。

**Comment by dotwell-inoue** [comment]
Slackとgithub間でコミュニケーション取れてない感じもありますし、
顔が見えないのもあるので特にコミュニケーションには気を付けたいですね。。。

**Comment by teppei696** [comment]
こちら反映済みなのでクローズします。
ご対応ありがとうございました！
