### ISSUE TITLE
データ自動更新 エラー報告

### ISSUE THREAD

**Issue by Yuukin256** [codeforosaka/covid19#345]
現状、GitHub Actions データ自動更新のエラーに気づいても共有する術が無いため、暫定的にこちらに Issue を立てます。

**Comment by Yuukin256** [comment]
@UedaShinichiro `patients_and_insoections.xlsx` の 1476 例目から 1491 例目 のところで、日付が文字列となって入力されています。よろしくお願いします。

**Comment by UedaShinichiro** [comment]
@Yuukin256 日付のところ、「ユーザ定義」書式でおこなっていたものが「日付」書式になっていました。そこを修正してアップしなおしています。これで様子みさせてください。お手数おかけします。。（列：発症日のところは「日付」書式だったんですね）

**Comment by Yuukin256** [comment]
@UedaShinichiro そうですね。これまでの形式にそのまま合わせていけば問題ないと思います

**Comment by teppei696** [comment]
こちら対応済みのため、クローズ
