### ISSUE TITLE
陽性者の属性にて年代でソートした時の並び順がおかしい

### ISSUE THREAD

**Issue by teppei696** [codeforosaka/covid19#354]
## 起こっている問題 / The Problem
- 陽性者の属性

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/1694558/80467168-6dd55600-8978-11ea-9bff-732edb178b19.png)

## 期待する見せ方・挙動 / Expected Behavior
- 以下のように並び替えられること
  - 未就学児→就学児→10代→〜〜〜〜90代→100代

## 起こっている問題の再現手段 / Steps to Reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mfmfuyu** [comment]
こちら対応しますね
