### ISSUE TITLE
日付形式の統一および翻訳について

### ISSUE THREAD

**Issue by Yuukin256** [codeforosaka/covid19#361]
## 改善詳細 / Details of Improvement
- 現在、様々な日付の形式が混在しており、また一部は翻訳に未対応 (英語でも `mm月dd日` と表記されてしまう) 

- [ ] 日付の形式を統一する

  - 1つに統一せずとも、使用位置ごとに適切な形式を決定する
  - 少なくとも修正したいもの
    - グラフによってツールチップの日付形式が異なる
    - グラフによって値の注釈が異なり `m/d 累計値` と `mm/dd の合計` がある
- [ ] 一部のグラフのツールチップが翻訳に未対応
  - `mm月dd日` 形式のまま英語で表示される
  - 「感染経路不明者（リンク不明者）」「新型コロナ受診相談センターへの相談件数」の積み上げ棒グラフ (`TimeStackedBarChart.vue` `TimeStackedBarChart2.vue`)

- 現在ある日付の形式
  - yyyy/mm/dd
  - m/d
  - mm/dd
  - mm月dd日

(`m` はゼロ埋めなしの月、 `mm` はゼロ埋めありの月。 `d` `dd` も同様)

## 期待する見せ方・挙動 / Expected behavior
- 統一された日付形式

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Yuukin256** [comment]
日時を全て [ISO 8601](https://ja.wikipedia.org/wiki/ISO_8601) 拡張形式に統一して扱い、日付を文字列として出力する時は、必ず関数を通す形式にすれば統一は容易だと思います。
正直なところ、日本語で無理に `m月d日` 形式にするよりも、全言語統一で `m/d` 形式にした方が管理が楽になるように思います。
「感染経路不明者（リンク不明者）」「新型コロナ受診相談センターへの相談件数」の英語表示のついでに統一したいのですが、どのような形式がよろしいでしょうか。

**Comment by teppei696** [comment]
issueありがとうございます。
確かに揃ってないですね。
全部```m/d```の形式にそろえてしまって良いと思います。

**Comment by Yuukin256** [comment]
- グラフのツールチップ
- グラフの右上注釈の「累計値」のところ
- 「陽性者の属性」の日付欄

を `m/d` 形式に統一します。
各カードのフッターにある `yyyyy/mm/dd` 時点の表示はそのままにします
