### ISSUE TITLE
スマホでお気に入りに登録すると東京都のアイコンが出てくる

### ISSUE THREAD

**Issue by teppei696** [codeforosaka/covid19#37]
## 起こっている問題 / The Problem
- スマホでお気に入りに登録すると東京都のアイコンが出てくる

## 期待する見せ方・挙動 / Expected Behavior
- 大阪府のアイコンがでてきて欲しい

## 起こっている問題の再現手段 / Steps to Reproduce
1. iPhoneでお気に入りに登録する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by y-chan** [comment]
https://github.com/codeforosaka/covid19/blob/development/static/apple-touch-icon-precomposed.png
ここの画像ファイルの替え忘れが問題になっているのではないでしょうか...?

**Comment by teppei696** [comment]
はい。今大阪府のアイコンを入手中です！
