### ISSUE TITLE
左画面「知事からのメッセージ」メニューのリンク先変更

### ISSUE THREAD

**Issue by UedaShinichiro** [codeforosaka/covid19#391]
## 改善詳細 / Details of Improvement
リンク先ページが公開終了してしまったので、以下へ変更お願いします。
http://www.pref.osaka.lg.jp/kikaku/message_governor/index.html

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Yuukin256** [comment]
対応しますー
