### ISSUE TITLE
Firefox利用時に読込中から画面が遷移しない

### ISSUE THREAD

**Issue by mofuwan0025** [codeforosaka/covid19#406]
## 起こっている問題 / The Problem
- Firefoxを利用時にリンクをクリックしても読込中の画面から遷移せずデータが表示されている画面を開くことができない。

## スクリーンショット / Screenshot
![コメント 2020-05-10 103825](https://user-images.githubusercontent.com/49588846/81488917-713adc80-92aa-11ea-921d-648525eca65e.png)

## 期待する見せ方・挙動 / Expected Behavior
- データ表示画面への遷移

## 起こっている問題の再現手段 / Steps to Reproduce
1. Firefoxを起動
2. https://covid19-osaka.info/ を開く
3. 読込中のまま遷移せず

## 動作環境・ブラウザ / Environment
- Windows 10 64bit 及び macOS Catalina 10.15.4
- Firefox 75.0

**Comment by teppei696** [comment]
ここっぽいですね。
対応します。
https://github.com/codeforosaka/covid19/blob/development/components/TimeStackedBarChart.vue#L150

**Comment by teppei696** [comment]
@mofuwan0025 こちら暫定対応が終わり、本番反映作業中です。
issue登録ありがとうございました！

**Comment by mofuwan0025** [comment]
お疲れ様です。ありがとうございます！

**Comment by mofuwan0025** [comment]
@teppei696 お疲れ様です。ありがとうございます！
