### ISSUE TITLE
検査陽性者の状況パネルの補足修正

### ISSUE THREAD

**Issue by UedaShinichiro** [codeforosaka/covid19#415]
## 改善詳細 / Details of Improvement
表の下の注釈について、以下のとおりお願いできますでしょうか。
※現在陽性者数には、府外で健康観察を実施している方を含む
※再陽性者を除く

なお、現在記載いただいている、
※現在陽性者数には状況確認中の方を含む
については、削除をお願いします。

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Yuukin256** [comment]
対応しますー

**Comment by UedaShinichiro** [comment]
@Yuukin256 対応ありがとうございました。プレビューで確認させてもらい、内容OKでした。
