### ISSUE TITLE
現在陽性者数の計算について

### ISSUE THREAD

**Issue by UedaShinichiro** [codeforosaka/covid19#419]
## 起こっている問題 / The Problem
「検査陽性者の状況」の表における「現在陽性者数」に府外健康観察の人数を加算してもらえるでしょうか。

patients_and_inspections.xlsxのピボット集計シートの23行目（Ｂ２３）に新たに府外健康観察の人数を追加しますので、それを追加で加算して現在陽性者数を出力いただけるでしょうか。
アップするファイルイメージを添付します。
[調整案patients_and_inspections.xlsx](https://github.com/codeforosaka/covid19/files/4625723/patients_and_inspections.xlsx)

## 期待する見せ方・挙動 / Expected Behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 起こっている問題の再現手段 / Steps to Reproduce
1. xxx
2. xxx
3. xxx

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by teppei696** [comment]
@UedaShinichiro こちらですが、ちょっと今日は難しいので明日以降に確認させてください。
修正内容としては「検査陽性者の状況」の中に新たに「府外健康観察」という欄をつくり、それを「現在陽性者数」の中に含めるという認識でよいでしょうか？

**Comment by UedaShinichiro** [comment]
@teppei696 「府外健康観察」という欄は設けなくて大丈夫です。「現在陽性者数」の計算ロジックだけ修正いただければと思います。

**Comment by teppei696** [comment]
今は
現在陽性者数 = 入院 + 入院調整中 + 自宅療養 + 宿泊療養 + 療養等調整中
となっているので、「府外健康観察」を上記のどこかに含めないと数値がおかしくなりそうな気が・・・

**Comment by UedaShinichiro** [comment]
ちょっと先走ってまして、「※現在陽性者数には、府外で健康観察を実施している方を含む」と入れています。本来は「入院調整中」に加えていた「府外健康観察」をわけてカウントしたいという先方の要望があり、現在陽性者数の計算式に「府外健康観察」を入れたいです。「府外健康観察」という欄を設けていれば、上記の補足はいらないのですが、そこまで個別に出したい数字というわけではないため、上記のような判断となっています。ややこしくてすいません。

**Comment by teppei696** [comment]
承知しました！
明日あたりには対応できると思います。

**Comment by UedaShinichiro** [comment]
すいません、よろしくお願いします。。

**Comment by teppei696** [comment]
@UedaShinichiro こちら開発環境にあげましたー
https://dev-covid19-osaka.netlify.app/

**Comment by UedaShinichiro** [comment]
@teppei696 ありがとうございます！計算結果、問題ありません。本番反映もお願いします。

**Comment by teppei696** [comment]
@UedaShinichiro 本番に反映中ですー
10〜15分で反映されると思いますー

**Comment by UedaShinichiro** [comment]
@teppei696 本番反映もありがとうございました。（今日もどこかのタイミングで陽性者情報の更新があると思います。また連絡させてもらいます。毎日申し訳ありません）

**Comment by teppei696** [comment]
これを対応したことによってIE11で正しく見えなくなったので、切り戻しを実施しました。
よって、再オープン

**Comment by teppei696** [comment]
そして明日あたりにやります。
