### ISSUE TITLE
リンク不明率がNaN %になっている

### ISSUE THREAD

**Issue by mfmfuyu** [codeforosaka/covid19#453]
## 起こっている問題 / The Problem
- 感染経路不明者（リンク不明者）のリンク不明率が`NaN %`と表示されている

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/54523771/83010271-f700ab00-a052-11ea-8615-59886815bd3e.png)

## 期待する見せ方・挙動 / Expected Behavior
- `0 %`と表示する

## 起こっている問題の再現手段 / Steps to Reproduce
 - 最新の感染経路不明者データが0人になっている時にページにアクセスする

**Comment by mfmfuyu** [comment]
こちら対応します

**Comment by teppei696** [comment]
ありがとうございます。
お願いします！
