### ISSUE TITLE
検査陽性者の状況のバーをグループ化する

### ISSUE THREAD

**Issue by Blue-Tone** [codeforosaka/covid19#463]
## 関連Issue
検査陽性者の状況のデザイン／集計方法変更 #266

## 改善詳細 / Details of Improvement
以前は縦のバーでグループ化していたが、横のバーになりデータのまとまりが分かりにくい。
[東京のサイト](https://stopcovid19.metro.tokyo.lg.jp/)を参考にバーをグループ化する。
[東京のソース](https://github.com/tokyo-metropolitan-gov/covid19)を流用できそう。

## スクリーンショット / Screenshot
大阪
<img width="596" alt="スクリーンショット 2020-05-30 13 02 48" src="https://user-images.githubusercontent.com/18328371/83319138-93ef5e00-a276-11ea-8e67-2e605da7a02f.png">

東京
<img width="596" alt="スクリーンショット 2020-05-30 13 02 27" src="https://user-images.githubusercontent.com/18328371/83319130-833ee800-a276-11ea-9426-43c73bce9276.png">

## 期待する見せ方・挙動 / Expected behavior
- 東京のサイトのような表示にする。

**Comment by teppei696** [comment]
遅くなりました、これやりましょー

**Comment by mfmfuyu** [comment]
こちら現在対応中です
