### ISSUE TITLE
[市区町村地図]凡例を地図で使用している色とリンクする

### ISSUE THREAD

**Issue by Blue-Tone** [codeforosaka/covid19#615]
## 親Issue
#281 市区町村毎の感染者数をビジュアルに表示したい

## 作業ブランチ
https://github.com/codeforosaka/covid19/tree/feature/municipality_map

## 改善詳細 / Details of Improvement
- 凡例が茨城のまま。凡例を地図で使用している色とリンクする。

## スクリーンショット / Screenshot
赤枠の部分を改修する。
![82126051-f95a3e00-97e4-11ea-9192-c9026f5c0f52](https://user-images.githubusercontent.com/18328371/90695821-27ed2680-e2b6-11ea-8c8f-9cab6d21fda9.png)

## 期待する見せ方・挙動 / Expected behavior
- 地図内の色と、判例の色をリンクさせる

## 動作環境・ブラウザ / Environment
- any

## 改修箇所
components/GraphicalMapCard.vue
この辺り。
https://github.com/codeforosaka/covid19/blob/4d367a28bdef777c3e997c8122f42039ced6ace4/components/GraphicalMapCard.vue#L12-L26

https://github.com/codeforosaka/covid19/blob/4d367a28bdef777c3e997c8122f42039ced6ace4/components/GraphicalMapCard.vue#L245-L250

https://github.com/codeforosaka/covid19/blob/4d367a28bdef777c3e997c8122f42039ced6ace4/components/GraphicalMapCard.vue#L96-L114

**Comment by Blue-Tone** [comment]
対応してくれる方、募集中です。

**Comment by yukiyaxxxx** [comment]
対応できそうなので作業します

**Comment by yukiyaxxxx** [comment]
変更完了したのでプルリク作成いたしました
https://github.com/codeforosaka/covid19/pull/625

**Comment by Blue-Tone** [comment]
マージしました。
ありがとうございます！
