### ISSUE TITLE
[市区町村地図]市町村をマウスオーバした時にポップアップで市町村名と値を表示する

### ISSUE THREAD

**Issue by yukiyaxxxx** [codeforosaka/covid19#635]
## 親issue
#281 市区町村毎の感染者数をビジュアルに表示したい

## 作業ブランチ
https://github.com/codeforosaka/covid19/tree/feature/municipality_map

## 改善詳細 / Details of Improvement
- 市町村地図にポップアップ追加

## スクリーンショット / Screenshot
![スクリーンショット 2020-08-28 16 38 47](https://user-images.githubusercontent.com/59367678/91534742-042c7f00-e94d-11ea-817d-f8b0836ab621.png)

## 期待する見せ方・挙動 / Expected behavior
- 市町村をマウスオーバした時にポップアップで市町村名と値を表示する

## 動作環境・ブラウザ / Environment
- any

**Comment by yukiyaxxxx** [comment]
対応します

**Comment by yukiyaxxxx** [comment]
プルリク作成しました
https://github.com/codeforosaka/covid19/pull/636

**Comment by Blue-Tone** [comment]
PRマージで解決済み。クローズします。

残件は以下で管理します。
[市区町村地図]河内長野市のホバーでのポップアップ表示不正 #683
