### ISSUE TITLE
[市区町村地図]data.jsonのデータを表示する

### ISSUE THREAD

**Issue by Blue-Tone** [codeforosaka/covid19#676]
## 親Issue
#281 市区町村毎の感染者数をビジュアルに表示したい

## 作業ブランチ
https://github.com/codeforosaka/covid19/tree/feature/municipality_map

## 改善詳細 / Details of Improvement
data.jsonの中のpatients.dataの居住地を集計し、元データとして地図に反映する。

#### data.json読み込み処理のコードがコメントアウトで残っている（茨城の？）
https://github.com/codeforosaka/covid19/blob/b6e7c5b48ec978b069e1415963ca0b653ab18b5b/components/GraphicalMapCard.vue#L56-L83

#### 陽生者データ読み込み箇所
https://github.com/codeforosaka/covid19/blob/b6e7c5b48ec978b069e1415963ca0b653ab18b5b/components/GraphicalMapCard.vue#L128

#### 地図データjson読込箇所
https://github.com/codeforosaka/covid19/blob/b6e7c5b48ec978b069e1415963ca0b653ab18b5b/components/GraphicalMapCard.vue#L187-L188

#### 地図データjson格納場所
https://github.com/codeforosaka/covid19/blob/feature/municipality_map/static/osakapref.json
[GeoJSON](https://ja.wikipedia.org/wiki/)というフォーマットで書かれている。
staticにおいているが、最終的にはdataのしたが良いかも？別途仕様調整する。

- [x] data.json読込む（既存処理を参考に）
- [x] 市区町村毎の感染者を集計（後で動的に期間でフィルタする機能を機能追加しそう？）
- [x] 地図に適用

## スクリーンショット / Screenshot
親Issue参照

## 期待する見せ方・挙動 / Expected behavior
- data.jsonの感染者数データが地図に反映されている。

## 動作環境・ブラウザ / Environment
- any

**Comment by Blue-Tone** [comment]
着手しています。

**Comment by Blue-Tone** [comment]
@teppei696 
集計する期間の仕様相談です。
現状は全ての期間の合計を表示しています。
https://deploy-preview-444--rev-covid19-osaka.netlify.app/

直近の１日、１週間、２週間ぐらいを表示するのが、現在の感染状況の把握に有用かと思いますが、要求仕様はありますか？

デフォルトは直近の１週間で良いでしょうか？
[奈良のサイト](https://stopcovid19.code4nara.org/)のように、期間を選択できるようにしてもいいでしょうか？

**Comment by Blue-Tone** [comment]
@teppei696
期間指定できるようにしてみました。
https://deploy-preview-688--rev-covid19-osaka.netlify.app/

こちらの方針で進めてもいいでしょうか？
OKでしたら、mapの本流ブランチにマージします。

**Comment by Blue-Tone** [comment]
残件は
[市区町村地図]集計の期間を変更可能にする #687
で管理します。

**Comment by teppei696** [comment]
@Blue-Tone こちら問題ありません。
ですので進めてしまってください。

ただ、先日大阪府の方より個人毎のデータ公開をやめるという話がきているため、データ取得元をどうするかを調整する必要があるので、少し大阪府の方と話をしてみます。
