### ISSUE TITLE
[市区町村地図]市町村の枠を白以外にして境界を見やすくする

### ISSUE THREAD

**Issue by Blue-Tone** [codeforosaka/covid19#686]
## 親Issue
#281 市区町村毎の感染者数をビジュアルに表示したい

## 作業ブランチ
https://github.com/codeforosaka/covid19/tree/feature/municipality_map

## 改善詳細 / Details of Improvement
- 市町村の枠を白以外（黒系？）にして境界を見やすくする

## スクリーンショット / Screenshot
11/10時点の現状の表示
![スクリーンショット 2020-11-10 9 58 46](https://user-images.githubusercontent.com/18328371/98614249-5cafcd80-233b-11eb-8825-b8723a51425a.png)

修正後のイメージ
![スクリーンショット 2020-05-12 9 39 27](https://user-images.githubusercontent.com/18328371/81625702-9ce9ce00-9434-11ea-990e-d9d6c939b908.png)

## 期待する見せ方・挙動 / Expected behavior
- 地図上に市町村名を表示されている

## 動作環境・ブラウザ / Environment
- any

**Comment by Blue-Tone** [comment]
誰か取れそうな人がいればご対応いただけると助かります。

**Comment by mfmfuyu** [comment]
こちらも #685 と併せて対応いたします

**Comment by Blue-Tone** [comment]
PRで修正済み。
ありがとうございました。

Deploy preview
https://deploy-preview-444--rev-covid19-osaka.netlify.app/
