### ISSUE TITLE
大阪府ＬＩＮＥ公式アカウントのメニュー追加

### ISSUE THREAD

**Issue by UedaShinichiro** [codeforosaka/covid19#69]
## 改善詳細 / Details of Improvement
大阪府公式Facebookメニューの下に、以下を追加いただけるでしょうか。

大阪府ＬＩＮＥ公式アカウント
https://lin.ee/8IJ5WMv

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by teppei696** [comment]
やりますー

**Comment by UedaShinichiro** [comment]
ありがとうございます！

**Comment by teppei696** [comment]
こちら対応完了しております。
https://covid19-osaka.info/
