### ISSUE TITLE
[市区町村地図]カードの表示領域を狭くすると地図表示がカードからはみ出して表示してしまう

### ISSUE THREAD

**Issue by Blue-Tone** [codeforosaka/covid19#691]
## 親Issue
#281 市区町村毎の感染者数をビジュアルに表示したい

## 作業ブランチ
https://github.com/codeforosaka/covid19/tree/feature/municipality_map

## 起こっている問題 / The Problem
- カードの表示領域を狭くすると地図表示がカードからはみ出して表示してしまう

## スクリーンショット / Screenshot
![スクリーンショット 2020-11-12 22 22 43](https://user-images.githubusercontent.com/18328371/98945380-c85d8a80-2535-11eb-8b53-de8b6c8b6be4.png)

## 期待する見せ方・挙動 / Expected Behavior
- カードからはみ出さないようにする

## 起こっている問題の再現手段 / Steps to Reproduce
1. ブラウザの表示幅を狭くする

## 動作環境・ブラウザ / Environment
- macOS
- Chrome
他は未確認。

**Comment by Blue-Tone** [comment]
誰か取れそうな人がいればご対応いただけると助かります。

**Comment by mfmfuyu** [comment]
こちらのIssueですが、#686 の対応途中でレスポンシブに対応できた為、#686 のPRをマージすれば同時に修正されます

**Comment by Blue-Tone** [comment]
PR #693 で修正済み。
ありがとうございました。

Deploy preview
https://deploy-preview-444--rev-covid19-osaka.netlify.app/
