### ISSUE TITLE
[市区町村地図]地図表示時のパフォーマンスが悪い、地図データの出典の表記がない

### ISSUE THREAD

**Issue by mfmfuyu** [codeforosaka/covid19#692]
## 改善詳細 / Details of Improvement
- 地図表示時のパフォーマンスが悪い
- 地図データは国土数値情報の「行政区域」を改変して使用しているようですが、出典が記載されていません。

## 期待する見せ方・挙動 / Expected behavior
- パフォーマンスを良くする
- 地図データの出典を記載する

**Comment by Blue-Tone** [comment]
PR #693 で修正済み。
ありがとうございました。

Deploy preview
https://deploy-preview-444--rev-covid19-osaka.netlify.app/
