### ISSUE TITLE
誤ってcodeforosakaブランチにコミット

### ISSUE THREAD

**Issue by UedaShinichiro** [codeforosaka/covid19#73]
## 改善詳細 / Details of Improvement
誤ってcodeforosakaブランチのNews.jsonにコミットしてしまったのですが、
キャンセルできるでしょうか？
（すみません）

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by teppei696** [comment]
@UedaShinichiro 
もう一度修正するためのプルリクを投げてもらっても良いでしょうか？

**Comment by UedaShinichiro** [comment]
@teppei696 
誤ってコミットしたものについては、プルリクしてないのですが、
これをプルリクしてから、再度修正のプルリクを投げるってことでしょうか？

**Comment by teppei696** [comment]
@UedaShinichiro 
あ、今のcodeforosaka/covidのnews.jsonが正解ってことで良いですかね？
で、あれば多分大丈夫だと思います。
https://covid19-osaka.info/
本番サイトでも反映されているんですよね？

**Comment by UedaShinichiro** [comment]
@teppei696 
＞今のcodeforosaka/covidのnews.jsonが正解ってことで良いですかね？
そうです。UedaShinichiro/covidでやるべきところだったのですが。。
本番サイトには反映されてないです。（まだプルリクしてないので）

あらためて、UedaShinichiro/covidでnews.jsonを修正してプルリクしたらよいですかね？

**Comment by teppei696** [comment]
@UedaShinichiro 
そうですね。お願いしてもよいでしょうか？

**Comment by UedaShinichiro** [comment]
もろもろ含めてプルリクしました。お願いいたします。

**Comment by teppei696** [comment]
プルリクしてもらったのでクローズ

**Comment by teppei696** [comment]
本番に反映終わりましたー
https://covid19-osaka.info/
