### ISSUE TITLE
更新日付について

### ISSUE THREAD

**Issue by UedaShinichiro** [codeforosaka/covid19#74]
## 改善詳細 / Details of Improvement
各データの集計日を掲載したいのですが、
各データの「2020/03/17 20:30更新」のところ「2020/03/17 時点」と
「更新」を「時点」に変えて、日時を出さないようにできるでしょうか？
（lastUpdateなので本来の趣旨と違いますが....）

なお、一番上の「最終更新日」欄だけは引き続き更新日として使えればと思います。
可能でしたらご検討お願いします。

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by teppei696** [comment]
こちら対応しますー

**Comment by teppei696** [comment]
@UedaShinichiro 
本番にあげたので少し確認してもらってよいでしょうか？
https://covid19-osaka.info/

**Comment by UedaShinichiro** [comment]
@teppei696 
イメージどおりです。ありがとうございます！
