### ISSUE TITLE
重症病床使用率のグラフが、100パーセント超えに対応していない。

### ISSUE THREAD

**Issue by shigobu** [codeforosaka/covid19#750]
## 起こっている問題 / The Problem
- 重症病床使用率のグラフが、100パーセント超えに対応していない。
グラフのマウスオーバーで表示される値は正確だが、右の縦軸の値が対応していない。
グラフの値は103パーセントだが、右の縦軸の80パーセントのちょい上に表示されている。

## スクリーンショット / Screenshot

![100パーセント超え](https://user-images.githubusercontent.com/32050537/117395837-b7fdf980-af33-11eb-8637-2dbb12ac400f.png)

## 期待する見せ方・挙動 / Expected Behavior
- 右縦軸の値を、100パーセント超えに対応させる。

## 起こっている問題の再現手段 / Steps to Reproduce
1. 大阪府新型コロナウイルス感染症対策サイトを表示する。

## 動作環境・ブラウザ / Environment
- Windows10 20H2
- Chrome バージョン: 90.0.4430.93

**Comment by teppei696** [comment]
こちら本番への反映おわりました！
ありがとうございました！
