### ISSUE TITLE
yarn devを行うとserverのビルドに失敗する

### ISSUE THREAD

**Issue by devchrist** [codeforosaka/covid19#756]
## 起こっている問題 / The Problem
- https://github.com/codeforosaka/covid19/commit/ce816cfc2d403f84b839a1ca1de36ad9417aba3eにて
ローカルで立ち上げると、ScrollableChart.vueのlabelCount()が原因でエラーとなる。

## スクリーンショット / Screenshot
<img width="1668" alt="スクリーンショット 2021-06-01 20 28 34" src="https://user-images.githubusercontent.com/7822668/120316098-02e31500-c318-11eb-8f74-cd9060634407.png">

## 期待する見せ方・挙動 / Expected Behavior
- Webサイトが正しく表示されること

## 起こっている問題の再現手段 / Steps to Reproduce
1. git clone 
2.  git checkout development
3. yarn install
4. yarn dev

## 動作環境・ブラウザ / Environment
- macOS 
- Chrome

**Comment by devchrist** [comment]
すみません。CONTRIBUTING.mdにあとから気がつきました。
開発します。

**Comment by whistyun** [comment]
再現に関してですが、nodeのバージョンによって発生するようです。
Windows環境ですが、
v10.19.0 (README.mdに書かている最小バージョン)では当事象は発生せず、
v14.17.0 (最新のLTS)では再現します。

**Comment by devchrist** [comment]
なるほど。
Package.jsonでは、>=10.19.0となっていたので、10.19.0以上なら問題ない仕様と捉えていました。
いずれにせよ、10.19.0はサポート終了しているので変える必要がありますね。

**Comment by devchrist** [comment]
> 再現に関してですが、nodeのバージョンによって発生するようです。
> Windows環境ですが、
> v10.19.0 (README.mdに書かている最小バージョン)では当事象は発生せず、
> v14.17.0 (最新のLTS)では再現します。

なるほど。
Package.jsonでは、>=10.19.0となっていたので、10.19.0以上なら問題ない仕様と捉えていました。
いずれにせよ、10.19.0はサポート終了しているので変える必要がありますね。
