### ISSUE TITLE
「新型コロナ受診相談センターへの相談件数」のデータの日付に誤りがある

### ISSUE THREAD

**Issue by aqua-ix** [codeforosaka/covid19#780]
## 起こっている問題 / The Problem

- 「新型コロナ受診相談センターへの相談件数」のグラフにおける 2022-01-31 の翌日のデータの日付が 2022-02-25 となっていますが、こちらは 2022-02-01 の誤りかと思われます。
https://github.com/codeforosaka/covid19/blob/b36101cfb6fb66e26720ffe9ec679a61045b6afb/static/data/contacts2.csv#L729
- [大阪府の窓口](https://www.shinsei.pref.osaka.lg.jp/ers/input?tetudukiId=2020030042) に問い合わせようかとも思いましたが、サイト運営に関わる方にご連絡した方が早いかと思い、こちらにてご報告させて頂きます。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/29789286/152180336-d75acaa5-da7a-4d97-974a-481ea7ed8284.png)

## 期待する見せ方・挙動 / Expected Behavior
- contacts2.csv の 2022-01-31 の翌日のデータの日付が 2022-02-01 であること。

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://covid19-osaka.info/ の 「新型コロナ受診相談センターへの相談件数」グラフから確認が可能。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by teppei696** [comment]
@aqua-ix こちらありがとうございます！元データを確認してみます！

**Comment by teppei696** [comment]
@aqua-ix こちらデータ提供元の修正間違いで発生しておりました。今は正しく更新されています！ご指摘ありがとうございました！

**Comment by aqua-ix** [comment]
@teppei696 
ありがとうございます！
私の方でも正しく更新されていることを確認しましたので、
本IssueはCloseさせて頂きます。
