### ISSUE TITLE
data.json が更新されていない。

### ISSUE THREAD

**Issue by mitsugu** [codeforosaka/covid19#822]
## 起こっている問題 / The Problem
- 64b9010029582d4eccc9de3a029017938561ca7b 以降 data.json が日付以外更新されていない。

## 期待する見せ方・挙動 / Expected Behavior
- 2022/11/19 日のデータを反映させるべき。

## 起こっている問題の再現手段 / Steps to Reproduce
See commit list

**Comment by teppei696** [comment]
@mitsugu issue登録ありがとうございます。
データは大阪府にて登録しております。
11/19分も大阪府でデータが揃い次第登録されると思いますのでお待ちください。

**Comment by teppei696** [comment]
こちら11/19分も更新されたのでクローズさせていただきます。
