### ISSUE TITLE
最終更新日時の修正

### ISSUE THREAD

**Issue by UedaShinichiro** [codeforosaka/covid19#84]
## 改善詳細 / Details of Improvement
最終更新日時が2020/03/16 20:50となっているのですが、
これを2020/03/18 15:45など、実際の最終更新日に近い時間帯にできるでしょうか？

## 期待する見せ方・挙動 / Expected behavior
- xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by teppei696** [comment]
@UedaShinichiro 
data.jsonの「lastUpdate」を変更していただければ反映されそうですー

**Comment by UedaShinichiro** [comment]
失礼しました。。再度あげますね。

**Comment by UedaShinichiro** [comment]
取り急ぎプリリクしました。

**Comment by teppei696** [comment]
本番反映終わったのでクローズしますー
