### ISSUE TITLE
検査実施人数と検査実施数の単位が違う、または数値が違う

### ISSUE THREAD

**Issue by mikkame** [codeforosaka/covid19#95]
## 起こっている問題 / The Problem

東京都のサイトでは下記の通りの解釈です。

- 実施検査人数　→ 検査した人の数、人
- 実施検査数　→ 検査した検体の数、件

検体数は、1人より複数回にわたる検体を採取する事があるため、人数より多くなるはずです。

## 期待する見せ方・挙動 / Expected Behavior
- 数値が正しいのなら単位を揃える
- 検体数のデータがないのなら人数に変更
- 検体数があるのならグラフに反映

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by teppei696** [comment]
ご指摘ありがとうございます。
大阪府に確認したところ、
「1人検査した場合、1件と数えるという方針」
「件数で揃えて欲しい」
という回答がありました。
大阪府のサイトでも上記考え方で統一しているため、その方向で修正する方向で動きたいと思います。

**Comment by teppei696** [comment]
なので、修正点としては
・検査実施数→検査実施件数
・検査実施人数→検査実施件数
という修正を実施いたします。
※ちなみに検体数のデータはありませんでした。
