### ISSUE TITLE
リポジトリへのリンク間違い

### ISSUE THREAD

**Issue by kwaka1208** [codeforosaka/covid19#96]
## 起こっている問題 / The Problem
- [当サイトについて](https://covid19-osaka.info/about)の中の「ソースコードについて」のGitHubリポジトリのリンク先が東京のリポジトリになっています。

## 期待する見せ方・挙動 / Expected Behavior
- リンク先を[大阪のリポジトリ](https://github.com/codeforosaka/covid19)に変更する。

## 起こっている問題の再現手段 / Steps to Reproduce
1. [当サイトについて](https://covid19-osaka.info/about)にアクセスする
2. 「ソースコードについて」のGitHubリポジトリのリンクをクリックする。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kwaka1208** [comment]
PR送りますね

**Comment by teppei696** [comment]
@kwaka1208 PRマージしました！
修正ありがとうございました！
